# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import coordinator_pb2 as coordinator__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/ddrl.comm.CoordinatorControl/RegisterWorker',
                request_serializer=coordinator__pb2.WorkerHello.SerializeToString,
                response_deserializer=coordinator__pb2.WorkerSession.FromString,
                _registered_method=True)
        self.RegisterLearner = channel.unary_unary(
                '/ddrl.comm.CoordinatorControl/RegisterLearner',
                request_serializer=coordinator__pb2.LearnerHello.SerializeToString,
                response_deserializer=coordinator__pb2.LearnerSession.FromString,
                _registered_method=True)
        self.WorkerHeartbeatStream = channel.stream_stream(
                '/ddrl.comm.CoordinatorControl/WorkerHeartbeatStream',
                request_serializer=coordinator__pb2.WorkerHeartbeat.SerializeToString,
                response_deserializer=coordinator__pb2.ControlDirective.FromString,
                _registered_method=True)
        self.LearnerHeartbeat = channel.unary_unary(
                '/ddrl.comm.CoordinatorControl/LearnerHeartbeat',
                request_serializer=coordinator__pb2.LearnerHeartbeatRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class CoordinatorControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterLearner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WorkerHeartbeatStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LearnerHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=coordinator__pb2.WorkerHello.FromString,
                    response_serializer=coordinator__pb2.WorkerSession.SerializeToString,
            ),
            'RegisterLearner': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterLearner,
                    request_deserializer=coordinator__pb2.LearnerHello.FromString,
                    response_serializer=coordinator__pb2.LearnerSession.SerializeToString,
            ),
            'WorkerHeartbeatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.WorkerHeartbeatStream,
                    request_deserializer=coordinator__pb2.WorkerHeartbeat.FromString,
                    response_serializer=coordinator__pb2.ControlDirective.SerializeToString,
            ),
            'LearnerHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.LearnerHeartbeat,
                    request_deserializer=coordinator__pb2.LearnerHeartbeatRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ddrl.comm.CoordinatorControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ddrl.comm.CoordinatorControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ddrl.comm.CoordinatorControl/RegisterWorker',
            coordinator__pb2.WorkerHello.SerializeToString,
            coordinator__pb2.WorkerSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterLearner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ddrl.comm.CoordinatorControl/RegisterLearner',
            coordinator__pb2.LearnerHello.SerializeToString,
            coordinator__pb2.LearnerSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WorkerHeartbeatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ddrl.comm.CoordinatorControl/WorkerHeartbeatStream',
            coordinator__pb2.WorkerHeartbeat.SerializeToString,
            coordinator__pb2.ControlDirective.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LearnerHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ddrl.comm.CoordinatorControl/LearnerHeartbeat',
            coordinator__pb2.LearnerHeartbeatRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
