# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: policy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'policy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpolicy.proto\x12\tddrl.comm\"H\n\x0cPolicyTensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\r\n\x05\x64type\x18\x04 \x01(\t\"\xde\x01\n\nPolicyPush\x12\x0f\n\x07version\x18\x01 \x01(\x04\x12,\n\x07tensors\x18\x02 \x03(\x0b\x32\x17.ddrl.comm.PolicyTensorB\x02\x18\x01\x12\x37\n\x07scalars\x18\x03 \x03(\x0b\x32\".ddrl.comm.PolicyPush.ScalarsEntryB\x02\x18\x01\x12\x14\n\x08metadata\x18\x04 \x01(\x0c\x42\x02\x18\x01\x12\x12\n\nonnx_model\x18\x05 \x01(\x0c\x1a.\n\x0cScalarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"T\n\x12PolicySubscription\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x15\n\rsession_token\x18\x02 \x01(\t\x12\x14\n\x0clast_version\x18\x03 \x01(\x04\"I\n\tPolicyAck\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12\x18\n\x10received_unix_ms\x18\x03 \x01(\x04\"y\n\x13PolicyStreamRequest\x12\x32\n\tsubscribe\x18\x01 \x01(\x0b\x32\x1d.ddrl.comm.PolicySubscriptionH\x00\x12#\n\x03\x61\x63k\x18\x02 \x01(\x0b\x32\x14.ddrl.comm.PolicyAckH\x00\x42\t\n\x07payload2a\n\rPolicyService\x12P\n\x13StreamPolicyUpdates\x12\x1e.ddrl.comm.PolicyStreamRequest\x1a\x15.ddrl.comm.PolicyPush(\x01\x30\x01\x42W\n\x0c\x61i.ddrl.commP\x01Z9github.com/ddrl/collision-avoidance/comm/gen/go/ddrl/comm\xaa\x02\tDdrl.Commb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'policy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014ai.ddrl.commP\001Z9github.com/ddrl/collision-avoidance/comm/gen/go/ddrl/comm\252\002\tDdrl.Comm'
  _globals['_POLICYPUSH_SCALARSENTRY']._loaded_options = None
  _globals['_POLICYPUSH_SCALARSENTRY']._serialized_options = b'8\001'
  _globals['_POLICYPUSH'].fields_by_name['tensors']._loaded_options = None
  _globals['_POLICYPUSH'].fields_by_name['tensors']._serialized_options = b'\030\001'
  _globals['_POLICYPUSH'].fields_by_name['scalars']._loaded_options = None
  _globals['_POLICYPUSH'].fields_by_name['scalars']._serialized_options = b'\030\001'
  _globals['_POLICYPUSH'].fields_by_name['metadata']._loaded_options = None
  _globals['_POLICYPUSH'].fields_by_name['metadata']._serialized_options = b'\030\001'
  _globals['_POLICYTENSOR']._serialized_start=27
  _globals['_POLICYTENSOR']._serialized_end=99
  _globals['_POLICYPUSH']._serialized_start=102
  _globals['_POLICYPUSH']._serialized_end=324
  _globals['_POLICYPUSH_SCALARSENTRY']._serialized_start=278
  _globals['_POLICYPUSH_SCALARSENTRY']._serialized_end=324
  _globals['_POLICYSUBSCRIPTION']._serialized_start=326
  _globals['_POLICYSUBSCRIPTION']._serialized_end=410
  _globals['_POLICYACK']._serialized_start=412
  _globals['_POLICYACK']._serialized_end=485
  _globals['_POLICYSTREAMREQUEST']._serialized_start=487
  _globals['_POLICYSTREAMREQUEST']._serialized_end=608
  _globals['_POLICYSERVICE']._serialized_start=610
  _globals['_POLICYSERVICE']._serialized_end=707
# @@protoc_insertion_point(module_scope)
