# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rollouts_pb2 as rollouts__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rollouts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RolloutStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRollouts = channel.stream_stream(
                '/ddrl.comm.RolloutStream/StreamRollouts',
                request_serializer=rollouts__pb2.RolloutStreamRequest.SerializeToString,
                response_deserializer=rollouts__pb2.RolloutStreamResponse.FromString,
                _registered_method=True)


class RolloutStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamRollouts(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RolloutStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamRollouts': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamRollouts,
                    request_deserializer=rollouts__pb2.RolloutStreamRequest.FromString,
                    response_serializer=rollouts__pb2.RolloutStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ddrl.comm.RolloutStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ddrl.comm.RolloutStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RolloutStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamRollouts(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ddrl.comm.RolloutStream/StreamRollouts',
            rollouts__pb2.RolloutStreamRequest.SerializeToString,
            rollouts__pb2.RolloutStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
