name: pole
category: structure
parts:
  - name: base
    geom:
      type: circle
      radius: 0.3
      z_min: 0.0
      z_max: 0.2
    material:
      name: pole_base
      rgba: [0.3, 0.3, 0.3, 1.0] # dark gray
    rel_pose:
      pos: [0.0, 0.0]
      yaw: 0.0

  - name: shaft
    geom:
      type: circle
      radius: 0.1
      z_min: 0.2
      z_max: 4.0
    material:
      name: pole_shaft
      rgba: [0.5, 0.5, 0.5, 1.0] # gray
    rel_pose:
      pos: [0.0, 0.0]
      yaw: 0.0
