// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: coordinator.proto
#ifndef GRPC_coordinator_2eproto__INCLUDED
#define GRPC_coordinator_2eproto__INCLUDED

#include "coordinator.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ddrl {
namespace comm {

class CoordinatorControl final {
 public:
  static constexpr char const* service_full_name() {
    return "ddrl.comm.CoordinatorControl";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::ddrl::comm::WorkerSession* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ddrl::comm::WorkerSession>> AsyncRegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ddrl::comm::WorkerSession>>(AsyncRegisterWorkerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ddrl::comm::WorkerSession>> PrepareAsyncRegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ddrl::comm::WorkerSession>>(PrepareAsyncRegisterWorkerRaw(context, request, cq));
    }
    virtual ::grpc::Status RegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::ddrl::comm::LearnerSession* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ddrl::comm::LearnerSession>> AsyncRegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ddrl::comm::LearnerSession>>(AsyncRegisterLearnerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ddrl::comm::LearnerSession>> PrepareAsyncRegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ddrl::comm::LearnerSession>>(PrepareAsyncRegisterLearnerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>> WorkerHeartbeatStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>>(WorkerHeartbeatStreamRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>> AsyncWorkerHeartbeatStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>>(AsyncWorkerHeartbeatStreamRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>> PrepareAsyncWorkerHeartbeatStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>>(PrepareAsyncWorkerHeartbeatStreamRaw(context, cq));
    }
    virtual ::grpc::Status LearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncLearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncLearnerHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncLearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncLearnerHeartbeatRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello* request, ::ddrl::comm::WorkerSession* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello* request, ::ddrl::comm::WorkerSession* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello* request, ::ddrl::comm::LearnerSession* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello* request, ::ddrl::comm::LearnerSession* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void WorkerHeartbeatStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ddrl::comm::WorkerHeartbeat,::ddrl::comm::ControlDirective>* reactor) = 0;
      virtual void LearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void LearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ddrl::comm::WorkerSession>* AsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ddrl::comm::WorkerSession>* PrepareAsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ddrl::comm::LearnerSession>* AsyncRegisterLearnerRaw(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ddrl::comm::LearnerSession>* PrepareAsyncRegisterLearnerRaw(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>* WorkerHeartbeatStreamRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>* AsyncWorkerHeartbeatStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>* PrepareAsyncWorkerHeartbeatStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncLearnerHeartbeatRaw(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncLearnerHeartbeatRaw(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::ddrl::comm::WorkerSession* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ddrl::comm::WorkerSession>> AsyncRegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ddrl::comm::WorkerSession>>(AsyncRegisterWorkerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ddrl::comm::WorkerSession>> PrepareAsyncRegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ddrl::comm::WorkerSession>>(PrepareAsyncRegisterWorkerRaw(context, request, cq));
    }
    ::grpc::Status RegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::ddrl::comm::LearnerSession* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ddrl::comm::LearnerSession>> AsyncRegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ddrl::comm::LearnerSession>>(AsyncRegisterLearnerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ddrl::comm::LearnerSession>> PrepareAsyncRegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ddrl::comm::LearnerSession>>(PrepareAsyncRegisterLearnerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>> WorkerHeartbeatStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>>(WorkerHeartbeatStreamRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>> AsyncWorkerHeartbeatStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>>(AsyncWorkerHeartbeatStreamRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>> PrepareAsyncWorkerHeartbeatStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>>(PrepareAsyncWorkerHeartbeatStreamRaw(context, cq));
    }
    ::grpc::Status LearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncLearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncLearnerHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncLearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncLearnerHeartbeatRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello* request, ::ddrl::comm::WorkerSession* response, std::function<void(::grpc::Status)>) override;
      void RegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello* request, ::ddrl::comm::WorkerSession* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello* request, ::ddrl::comm::LearnerSession* response, std::function<void(::grpc::Status)>) override;
      void RegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello* request, ::ddrl::comm::LearnerSession* response, ::grpc::ClientUnaryReactor* reactor) override;
      void WorkerHeartbeatStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ddrl::comm::WorkerHeartbeat,::ddrl::comm::ControlDirective>* reactor) override;
      void LearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void LearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ddrl::comm::WorkerSession>* AsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ddrl::comm::WorkerSession>* PrepareAsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ddrl::comm::LearnerSession>* AsyncRegisterLearnerRaw(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ddrl::comm::LearnerSession>* PrepareAsyncRegisterLearnerRaw(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>* WorkerHeartbeatStreamRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>* AsyncWorkerHeartbeatStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>* PrepareAsyncWorkerHeartbeatStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncLearnerHeartbeatRaw(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncLearnerHeartbeatRaw(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterWorker_;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterLearner_;
    const ::grpc::internal::RpcMethod rpcmethod_WorkerHeartbeatStream_;
    const ::grpc::internal::RpcMethod rpcmethod_LearnerHeartbeat_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RegisterWorker(::grpc::ServerContext* context, const ::ddrl::comm::WorkerHello* request, ::ddrl::comm::WorkerSession* response);
    virtual ::grpc::Status RegisterLearner(::grpc::ServerContext* context, const ::ddrl::comm::LearnerHello* request, ::ddrl::comm::LearnerSession* response);
    virtual ::grpc::Status WorkerHeartbeatStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ddrl::comm::ControlDirective, ::ddrl::comm::WorkerHeartbeat>* stream);
    virtual ::grpc::Status LearnerHeartbeat(::grpc::ServerContext* context, const ::ddrl::comm::LearnerHeartbeatRequest* request, ::google::protobuf::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::ddrl::comm::WorkerHello* /*request*/, ::ddrl::comm::WorkerSession* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterWorker(::grpc::ServerContext* context, ::ddrl::comm::WorkerHello* request, ::grpc::ServerAsyncResponseWriter< ::ddrl::comm::WorkerSession>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterLearner : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterLearner() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RegisterLearner() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterLearner(::grpc::ServerContext* /*context*/, const ::ddrl::comm::LearnerHello* /*request*/, ::ddrl::comm::LearnerSession* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterLearner(::grpc::ServerContext* context, ::ddrl::comm::LearnerHello* request, ::grpc::ServerAsyncResponseWriter< ::ddrl::comm::LearnerSession>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_WorkerHeartbeatStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_WorkerHeartbeatStream() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_WorkerHeartbeatStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WorkerHeartbeatStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::ControlDirective, ::ddrl::comm::WorkerHeartbeat>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWorkerHeartbeatStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::ddrl::comm::ControlDirective, ::ddrl::comm::WorkerHeartbeat>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_LearnerHeartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_LearnerHeartbeat() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_LearnerHeartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LearnerHeartbeat(::grpc::ServerContext* /*context*/, const ::ddrl::comm::LearnerHeartbeatRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLearnerHeartbeat(::grpc::ServerContext* context, ::ddrl::comm::LearnerHeartbeatRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegisterWorker<WithAsyncMethod_RegisterLearner<WithAsyncMethod_WorkerHeartbeatStream<WithAsyncMethod_LearnerHeartbeat<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ddrl::comm::WorkerHello, ::ddrl::comm::WorkerSession>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ddrl::comm::WorkerHello* request, ::ddrl::comm::WorkerSession* response) { return this->RegisterWorker(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterWorker(
        ::grpc::MessageAllocator< ::ddrl::comm::WorkerHello, ::ddrl::comm::WorkerSession>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ddrl::comm::WorkerHello, ::ddrl::comm::WorkerSession>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::ddrl::comm::WorkerHello* /*request*/, ::ddrl::comm::WorkerSession* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterWorker(
      ::grpc::CallbackServerContext* /*context*/, const ::ddrl::comm::WorkerHello* /*request*/, ::ddrl::comm::WorkerSession* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RegisterLearner : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterLearner() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ddrl::comm::LearnerHello, ::ddrl::comm::LearnerSession>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ddrl::comm::LearnerHello* request, ::ddrl::comm::LearnerSession* response) { return this->RegisterLearner(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterLearner(
        ::grpc::MessageAllocator< ::ddrl::comm::LearnerHello, ::ddrl::comm::LearnerSession>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ddrl::comm::LearnerHello, ::ddrl::comm::LearnerSession>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterLearner() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterLearner(::grpc::ServerContext* /*context*/, const ::ddrl::comm::LearnerHello* /*request*/, ::ddrl::comm::LearnerSession* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterLearner(
      ::grpc::CallbackServerContext* /*context*/, const ::ddrl::comm::LearnerHello* /*request*/, ::ddrl::comm::LearnerSession* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_WorkerHeartbeatStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_WorkerHeartbeatStream() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->WorkerHeartbeatStream(context); }));
    }
    ~WithCallbackMethod_WorkerHeartbeatStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WorkerHeartbeatStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::ControlDirective, ::ddrl::comm::WorkerHeartbeat>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>* WorkerHeartbeatStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_LearnerHeartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_LearnerHeartbeat() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::ddrl::comm::LearnerHeartbeatRequest, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ddrl::comm::LearnerHeartbeatRequest* request, ::google::protobuf::Empty* response) { return this->LearnerHeartbeat(context, request, response); }));}
    void SetMessageAllocatorFor_LearnerHeartbeat(
        ::grpc::MessageAllocator< ::ddrl::comm::LearnerHeartbeatRequest, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ddrl::comm::LearnerHeartbeatRequest, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_LearnerHeartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LearnerHeartbeat(::grpc::ServerContext* /*context*/, const ::ddrl::comm::LearnerHeartbeatRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* LearnerHeartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::ddrl::comm::LearnerHeartbeatRequest* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RegisterWorker<WithCallbackMethod_RegisterLearner<WithCallbackMethod_WorkerHeartbeatStream<WithCallbackMethod_LearnerHeartbeat<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::ddrl::comm::WorkerHello* /*request*/, ::ddrl::comm::WorkerSession* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RegisterLearner : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterLearner() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RegisterLearner() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterLearner(::grpc::ServerContext* /*context*/, const ::ddrl::comm::LearnerHello* /*request*/, ::ddrl::comm::LearnerSession* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_WorkerHeartbeatStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_WorkerHeartbeatStream() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_WorkerHeartbeatStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WorkerHeartbeatStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::ControlDirective, ::ddrl::comm::WorkerHeartbeat>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_LearnerHeartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_LearnerHeartbeat() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_LearnerHeartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LearnerHeartbeat(::grpc::ServerContext* /*context*/, const ::ddrl::comm::LearnerHeartbeatRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::ddrl::comm::WorkerHello* /*request*/, ::ddrl::comm::WorkerSession* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterWorker(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterLearner : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterLearner() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RegisterLearner() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterLearner(::grpc::ServerContext* /*context*/, const ::ddrl::comm::LearnerHello* /*request*/, ::ddrl::comm::LearnerSession* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterLearner(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_WorkerHeartbeatStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_WorkerHeartbeatStream() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_WorkerHeartbeatStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WorkerHeartbeatStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::ControlDirective, ::ddrl::comm::WorkerHeartbeat>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWorkerHeartbeatStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_LearnerHeartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_LearnerHeartbeat() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_LearnerHeartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LearnerHeartbeat(::grpc::ServerContext* /*context*/, const ::ddrl::comm::LearnerHeartbeatRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLearnerHeartbeat(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterWorker(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::ddrl::comm::WorkerHello* /*request*/, ::ddrl::comm::WorkerSession* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterWorker(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterLearner : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterLearner() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterLearner(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterLearner() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterLearner(::grpc::ServerContext* /*context*/, const ::ddrl::comm::LearnerHello* /*request*/, ::ddrl::comm::LearnerSession* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterLearner(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_WorkerHeartbeatStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_WorkerHeartbeatStream() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->WorkerHeartbeatStream(context); }));
    }
    ~WithRawCallbackMethod_WorkerHeartbeatStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WorkerHeartbeatStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::ControlDirective, ::ddrl::comm::WorkerHeartbeat>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* WorkerHeartbeatStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_LearnerHeartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_LearnerHeartbeat() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->LearnerHeartbeat(context, request, response); }));
    }
    ~WithRawCallbackMethod_LearnerHeartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LearnerHeartbeat(::grpc::ServerContext* /*context*/, const ::ddrl::comm::LearnerHeartbeatRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* LearnerHeartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ddrl::comm::WorkerHello, ::ddrl::comm::WorkerSession>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ddrl::comm::WorkerHello, ::ddrl::comm::WorkerSession>* streamer) {
                       return this->StreamedRegisterWorker(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::ddrl::comm::WorkerHello* /*request*/, ::ddrl::comm::WorkerSession* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterWorker(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ddrl::comm::WorkerHello,::ddrl::comm::WorkerSession>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterLearner : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterLearner() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ddrl::comm::LearnerHello, ::ddrl::comm::LearnerSession>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ddrl::comm::LearnerHello, ::ddrl::comm::LearnerSession>* streamer) {
                       return this->StreamedRegisterLearner(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterLearner() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterLearner(::grpc::ServerContext* /*context*/, const ::ddrl::comm::LearnerHello* /*request*/, ::ddrl::comm::LearnerSession* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterLearner(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ddrl::comm::LearnerHello,::ddrl::comm::LearnerSession>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_LearnerHeartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_LearnerHeartbeat() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ddrl::comm::LearnerHeartbeatRequest, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ddrl::comm::LearnerHeartbeatRequest, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedLearnerHeartbeat(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_LearnerHeartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status LearnerHeartbeat(::grpc::ServerContext* /*context*/, const ::ddrl::comm::LearnerHeartbeatRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLearnerHeartbeat(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ddrl::comm::LearnerHeartbeatRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegisterWorker<WithStreamedUnaryMethod_RegisterLearner<WithStreamedUnaryMethod_LearnerHeartbeat<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegisterWorker<WithStreamedUnaryMethod_RegisterLearner<WithStreamedUnaryMethod_LearnerHeartbeat<Service > > > StreamedService;
};

}  // namespace comm
}  // namespace ddrl


#endif  // GRPC_coordinator_2eproto__INCLUDED
