// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: coordinator.proto

#include "coordinator.pb.h"
#include "coordinator.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ddrl {
namespace comm {

static const char* CoordinatorControl_method_names[] = {
  "/ddrl.comm.CoordinatorControl/RegisterWorker",
  "/ddrl.comm.CoordinatorControl/RegisterLearner",
  "/ddrl.comm.CoordinatorControl/WorkerHeartbeatStream",
  "/ddrl.comm.CoordinatorControl/LearnerHeartbeat",
};

std::unique_ptr< CoordinatorControl::Stub> CoordinatorControl::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CoordinatorControl::Stub> stub(new CoordinatorControl::Stub(channel, options));
  return stub;
}

CoordinatorControl::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RegisterWorker_(CoordinatorControl_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterLearner_(CoordinatorControl_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WorkerHeartbeatStream_(CoordinatorControl_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_LearnerHeartbeat_(CoordinatorControl_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CoordinatorControl::Stub::RegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::ddrl::comm::WorkerSession* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ddrl::comm::WorkerHello, ::ddrl::comm::WorkerSession, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterWorker_, context, request, response);
}

void CoordinatorControl::Stub::async::RegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello* request, ::ddrl::comm::WorkerSession* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ddrl::comm::WorkerHello, ::ddrl::comm::WorkerSession, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterWorker_, context, request, response, std::move(f));
}

void CoordinatorControl::Stub::async::RegisterWorker(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello* request, ::ddrl::comm::WorkerSession* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterWorker_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ddrl::comm::WorkerSession>* CoordinatorControl::Stub::PrepareAsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ddrl::comm::WorkerSession, ::ddrl::comm::WorkerHello, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterWorker_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ddrl::comm::WorkerSession>* CoordinatorControl::Stub::AsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::ddrl::comm::WorkerHello& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterWorkerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CoordinatorControl::Stub::RegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::ddrl::comm::LearnerSession* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ddrl::comm::LearnerHello, ::ddrl::comm::LearnerSession, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterLearner_, context, request, response);
}

void CoordinatorControl::Stub::async::RegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello* request, ::ddrl::comm::LearnerSession* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ddrl::comm::LearnerHello, ::ddrl::comm::LearnerSession, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterLearner_, context, request, response, std::move(f));
}

void CoordinatorControl::Stub::async::RegisterLearner(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello* request, ::ddrl::comm::LearnerSession* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterLearner_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ddrl::comm::LearnerSession>* CoordinatorControl::Stub::PrepareAsyncRegisterLearnerRaw(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ddrl::comm::LearnerSession, ::ddrl::comm::LearnerHello, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterLearner_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ddrl::comm::LearnerSession>* CoordinatorControl::Stub::AsyncRegisterLearnerRaw(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHello& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterLearnerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>* CoordinatorControl::Stub::WorkerHeartbeatStreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>::Create(channel_.get(), rpcmethod_WorkerHeartbeatStream_, context);
}

void CoordinatorControl::Stub::async::WorkerHeartbeatStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ddrl::comm::WorkerHeartbeat,::ddrl::comm::ControlDirective>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::ddrl::comm::WorkerHeartbeat,::ddrl::comm::ControlDirective>::Create(stub_->channel_.get(), stub_->rpcmethod_WorkerHeartbeatStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>* CoordinatorControl::Stub::AsyncWorkerHeartbeatStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>::Create(channel_.get(), cq, rpcmethod_WorkerHeartbeatStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>* CoordinatorControl::Stub::PrepareAsyncWorkerHeartbeatStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>::Create(channel_.get(), cq, rpcmethod_WorkerHeartbeatStream_, context, false, nullptr);
}

::grpc::Status CoordinatorControl::Stub::LearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ddrl::comm::LearnerHeartbeatRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LearnerHeartbeat_, context, request, response);
}

void CoordinatorControl::Stub::async::LearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ddrl::comm::LearnerHeartbeatRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LearnerHeartbeat_, context, request, response, std::move(f));
}

void CoordinatorControl::Stub::async::LearnerHeartbeat(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LearnerHeartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* CoordinatorControl::Stub::PrepareAsyncLearnerHeartbeatRaw(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::ddrl::comm::LearnerHeartbeatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LearnerHeartbeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* CoordinatorControl::Stub::AsyncLearnerHeartbeatRaw(::grpc::ClientContext* context, const ::ddrl::comm::LearnerHeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLearnerHeartbeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

CoordinatorControl::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CoordinatorControl_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CoordinatorControl::Service, ::ddrl::comm::WorkerHello, ::ddrl::comm::WorkerSession, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CoordinatorControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ddrl::comm::WorkerHello* req,
             ::ddrl::comm::WorkerSession* resp) {
               return service->RegisterWorker(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CoordinatorControl_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CoordinatorControl::Service, ::ddrl::comm::LearnerHello, ::ddrl::comm::LearnerSession, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CoordinatorControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ddrl::comm::LearnerHello* req,
             ::ddrl::comm::LearnerSession* resp) {
               return service->RegisterLearner(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CoordinatorControl_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< CoordinatorControl::Service, ::ddrl::comm::WorkerHeartbeat, ::ddrl::comm::ControlDirective>(
          [](CoordinatorControl::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::ddrl::comm::ControlDirective,
             ::ddrl::comm::WorkerHeartbeat>* stream) {
               return service->WorkerHeartbeatStream(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CoordinatorControl_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CoordinatorControl::Service, ::ddrl::comm::LearnerHeartbeatRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CoordinatorControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ddrl::comm::LearnerHeartbeatRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->LearnerHeartbeat(ctx, req, resp);
             }, this)));
}

CoordinatorControl::Service::~Service() {
}

::grpc::Status CoordinatorControl::Service::RegisterWorker(::grpc::ServerContext* context, const ::ddrl::comm::WorkerHello* request, ::ddrl::comm::WorkerSession* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CoordinatorControl::Service::RegisterLearner(::grpc::ServerContext* context, const ::ddrl::comm::LearnerHello* request, ::ddrl::comm::LearnerSession* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CoordinatorControl::Service::WorkerHeartbeatStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ddrl::comm::ControlDirective, ::ddrl::comm::WorkerHeartbeat>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CoordinatorControl::Service::LearnerHeartbeat(::grpc::ServerContext* context, const ::ddrl::comm::LearnerHeartbeatRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ddrl
}  // namespace comm

