// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_policy_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_policy_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_policy_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_policy_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_policy_2eproto;
namespace ddrl {
namespace comm {
class PolicyAck;
struct PolicyAckDefaultTypeInternal;
extern PolicyAckDefaultTypeInternal _PolicyAck_default_instance_;
class PolicyPush;
struct PolicyPushDefaultTypeInternal;
extern PolicyPushDefaultTypeInternal _PolicyPush_default_instance_;
class PolicyPush_ScalarsEntry_DoNotUse;
struct PolicyPush_ScalarsEntry_DoNotUseDefaultTypeInternal;
extern PolicyPush_ScalarsEntry_DoNotUseDefaultTypeInternal _PolicyPush_ScalarsEntry_DoNotUse_default_instance_;
class PolicyStreamRequest;
struct PolicyStreamRequestDefaultTypeInternal;
extern PolicyStreamRequestDefaultTypeInternal _PolicyStreamRequest_default_instance_;
class PolicySubscription;
struct PolicySubscriptionDefaultTypeInternal;
extern PolicySubscriptionDefaultTypeInternal _PolicySubscription_default_instance_;
class PolicyTensor;
struct PolicyTensorDefaultTypeInternal;
extern PolicyTensorDefaultTypeInternal _PolicyTensor_default_instance_;
}  // namespace comm
}  // namespace ddrl
PROTOBUF_NAMESPACE_OPEN
template<> ::ddrl::comm::PolicyAck* Arena::CreateMaybeMessage<::ddrl::comm::PolicyAck>(Arena*);
template<> ::ddrl::comm::PolicyPush* Arena::CreateMaybeMessage<::ddrl::comm::PolicyPush>(Arena*);
template<> ::ddrl::comm::PolicyPush_ScalarsEntry_DoNotUse* Arena::CreateMaybeMessage<::ddrl::comm::PolicyPush_ScalarsEntry_DoNotUse>(Arena*);
template<> ::ddrl::comm::PolicyStreamRequest* Arena::CreateMaybeMessage<::ddrl::comm::PolicyStreamRequest>(Arena*);
template<> ::ddrl::comm::PolicySubscription* Arena::CreateMaybeMessage<::ddrl::comm::PolicySubscription>(Arena*);
template<> ::ddrl::comm::PolicyTensor* Arena::CreateMaybeMessage<::ddrl::comm::PolicyTensor>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ddrl {
namespace comm {

// ===================================================================

class PolicyTensor final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ddrl.comm.PolicyTensor) */ {
 public:
  inline PolicyTensor() : PolicyTensor(nullptr) {}
  ~PolicyTensor() override;
  explicit PROTOBUF_CONSTEXPR PolicyTensor(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PolicyTensor(const PolicyTensor& from);
  PolicyTensor(PolicyTensor&& from) noexcept
    : PolicyTensor() {
    *this = ::std::move(from);
  }

  inline PolicyTensor& operator=(const PolicyTensor& from) {
    CopyFrom(from);
    return *this;
  }
  inline PolicyTensor& operator=(PolicyTensor&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PolicyTensor& default_instance() {
    return *internal_default_instance();
  }
  static inline const PolicyTensor* internal_default_instance() {
    return reinterpret_cast<const PolicyTensor*>(
               &_PolicyTensor_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PolicyTensor& a, PolicyTensor& b) {
    a.Swap(&b);
  }
  inline void Swap(PolicyTensor* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PolicyTensor* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PolicyTensor* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PolicyTensor>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PolicyTensor& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PolicyTensor& from) {
    PolicyTensor::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PolicyTensor* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ddrl.comm.PolicyTensor";
  }
  protected:
  explicit PolicyTensor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShapeFieldNumber = 2,
    kNameFieldNumber = 1,
    kDataFieldNumber = 3,
    kDtypeFieldNumber = 4,
  };
  // repeated int32 shape = 2;
  int shape_size() const;
  private:
  int _internal_shape_size() const;
  public:
  void clear_shape();
  private:
  int32_t _internal_shape(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_shape() const;
  void _internal_add_shape(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_shape();
  public:
  int32_t shape(int index) const;
  void set_shape(int index, int32_t value);
  void add_shape(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      shape() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_shape();

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // string dtype = 4;
  void clear_dtype();
  const std::string& dtype() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dtype(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dtype();
  PROTOBUF_NODISCARD std::string* release_dtype();
  void set_allocated_dtype(std::string* dtype);
  private:
  const std::string& _internal_dtype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dtype(const std::string& value);
  std::string* _internal_mutable_dtype();
  public:

  // @@protoc_insertion_point(class_scope:ddrl.comm.PolicyTensor)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > shape_;
    mutable std::atomic<int> _shape_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dtype_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_policy_2eproto;
};
// -------------------------------------------------------------------

class PolicyPush_ScalarsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PolicyPush_ScalarsEntry_DoNotUse, 
    std::string, double,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PolicyPush_ScalarsEntry_DoNotUse, 
    std::string, double,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE> SuperType;
  PolicyPush_ScalarsEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR PolicyPush_ScalarsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit PolicyPush_ScalarsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const PolicyPush_ScalarsEntry_DoNotUse& other);
  static const PolicyPush_ScalarsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PolicyPush_ScalarsEntry_DoNotUse*>(&_PolicyPush_ScalarsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "ddrl.comm.PolicyPush.ScalarsEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_policy_2eproto;
};

// -------------------------------------------------------------------

class PolicyPush final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ddrl.comm.PolicyPush) */ {
 public:
  inline PolicyPush() : PolicyPush(nullptr) {}
  ~PolicyPush() override;
  explicit PROTOBUF_CONSTEXPR PolicyPush(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PolicyPush(const PolicyPush& from);
  PolicyPush(PolicyPush&& from) noexcept
    : PolicyPush() {
    *this = ::std::move(from);
  }

  inline PolicyPush& operator=(const PolicyPush& from) {
    CopyFrom(from);
    return *this;
  }
  inline PolicyPush& operator=(PolicyPush&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PolicyPush& default_instance() {
    return *internal_default_instance();
  }
  static inline const PolicyPush* internal_default_instance() {
    return reinterpret_cast<const PolicyPush*>(
               &_PolicyPush_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PolicyPush& a, PolicyPush& b) {
    a.Swap(&b);
  }
  inline void Swap(PolicyPush* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PolicyPush* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PolicyPush* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PolicyPush>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PolicyPush& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PolicyPush& from) {
    PolicyPush::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PolicyPush* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ddrl.comm.PolicyPush";
  }
  protected:
  explicit PolicyPush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kTensorsFieldNumber = 2,
    kScalarsFieldNumber = 3,
    kMetadataFieldNumber = 4,
    kOnnxModelFieldNumber = 5,
    kVersionFieldNumber = 1,
  };
  // repeated .ddrl.comm.PolicyTensor tensors = 2 [deprecated = true];
  PROTOBUF_DEPRECATED int tensors_size() const;
  private:
  int _internal_tensors_size() const;
  public:
  PROTOBUF_DEPRECATED void clear_tensors();
  PROTOBUF_DEPRECATED ::ddrl::comm::PolicyTensor* mutable_tensors(int index);
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ddrl::comm::PolicyTensor >*
      mutable_tensors();
  private:
  const ::ddrl::comm::PolicyTensor& _internal_tensors(int index) const;
  ::ddrl::comm::PolicyTensor* _internal_add_tensors();
  public:
  PROTOBUF_DEPRECATED const ::ddrl::comm::PolicyTensor& tensors(int index) const;
  PROTOBUF_DEPRECATED ::ddrl::comm::PolicyTensor* add_tensors();
  PROTOBUF_DEPRECATED const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ddrl::comm::PolicyTensor >&
      tensors() const;

  // map<string, double> scalars = 3 [deprecated = true];
  PROTOBUF_DEPRECATED int scalars_size() const;
  private:
  int _internal_scalars_size() const;
  public:
  PROTOBUF_DEPRECATED void clear_scalars();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >&
      _internal_scalars() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >*
      _internal_mutable_scalars();
  public:
  PROTOBUF_DEPRECATED const ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >&
      scalars() const;
  PROTOBUF_DEPRECATED ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >*
      mutable_scalars();

  // bytes metadata = 4 [deprecated = true];
  PROTOBUF_DEPRECATED void clear_metadata();
  PROTOBUF_DEPRECATED const std::string& metadata() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  PROTOBUF_DEPRECATED void set_metadata(ArgT0&& arg0, ArgT... args);
  PROTOBUF_DEPRECATED std::string* mutable_metadata();
  PROTOBUF_NODISCARD PROTOBUF_DEPRECATED std::string* release_metadata();
  PROTOBUF_DEPRECATED void set_allocated_metadata(std::string* metadata);
  private:
  const std::string& _internal_metadata() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_metadata(const std::string& value);
  std::string* _internal_mutable_metadata();
  public:

  // bytes onnx_model = 5;
  void clear_onnx_model();
  const std::string& onnx_model() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_onnx_model(ArgT0&& arg0, ArgT... args);
  std::string* mutable_onnx_model();
  PROTOBUF_NODISCARD std::string* release_onnx_model();
  void set_allocated_onnx_model(std::string* onnx_model);
  private:
  const std::string& _internal_onnx_model() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_onnx_model(const std::string& value);
  std::string* _internal_mutable_onnx_model();
  public:

  // uint64 version = 1;
  void clear_version();
  uint64_t version() const;
  void set_version(uint64_t value);
  private:
  uint64_t _internal_version() const;
  void _internal_set_version(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:ddrl.comm.PolicyPush)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ddrl::comm::PolicyTensor > tensors_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        PolicyPush_ScalarsEntry_DoNotUse,
        std::string, double,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE> scalars_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr metadata_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr onnx_model_;
    uint64_t version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_policy_2eproto;
};
// -------------------------------------------------------------------

class PolicySubscription final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ddrl.comm.PolicySubscription) */ {
 public:
  inline PolicySubscription() : PolicySubscription(nullptr) {}
  ~PolicySubscription() override;
  explicit PROTOBUF_CONSTEXPR PolicySubscription(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PolicySubscription(const PolicySubscription& from);
  PolicySubscription(PolicySubscription&& from) noexcept
    : PolicySubscription() {
    *this = ::std::move(from);
  }

  inline PolicySubscription& operator=(const PolicySubscription& from) {
    CopyFrom(from);
    return *this;
  }
  inline PolicySubscription& operator=(PolicySubscription&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PolicySubscription& default_instance() {
    return *internal_default_instance();
  }
  static inline const PolicySubscription* internal_default_instance() {
    return reinterpret_cast<const PolicySubscription*>(
               &_PolicySubscription_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PolicySubscription& a, PolicySubscription& b) {
    a.Swap(&b);
  }
  inline void Swap(PolicySubscription* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PolicySubscription* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PolicySubscription* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PolicySubscription>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PolicySubscription& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PolicySubscription& from) {
    PolicySubscription::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PolicySubscription* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ddrl.comm.PolicySubscription";
  }
  protected:
  explicit PolicySubscription(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWorkerIdFieldNumber = 1,
    kSessionTokenFieldNumber = 2,
    kLastVersionFieldNumber = 3,
  };
  // string worker_id = 1;
  void clear_worker_id();
  const std::string& worker_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_worker_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_worker_id();
  PROTOBUF_NODISCARD std::string* release_worker_id();
  void set_allocated_worker_id(std::string* worker_id);
  private:
  const std::string& _internal_worker_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_worker_id(const std::string& value);
  std::string* _internal_mutable_worker_id();
  public:

  // string session_token = 2;
  void clear_session_token();
  const std::string& session_token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_token();
  PROTOBUF_NODISCARD std::string* release_session_token();
  void set_allocated_session_token(std::string* session_token);
  private:
  const std::string& _internal_session_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_token(const std::string& value);
  std::string* _internal_mutable_session_token();
  public:

  // uint64 last_version = 3;
  void clear_last_version();
  uint64_t last_version() const;
  void set_last_version(uint64_t value);
  private:
  uint64_t _internal_last_version() const;
  void _internal_set_last_version(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:ddrl.comm.PolicySubscription)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr worker_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_token_;
    uint64_t last_version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_policy_2eproto;
};
// -------------------------------------------------------------------

class PolicyAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ddrl.comm.PolicyAck) */ {
 public:
  inline PolicyAck() : PolicyAck(nullptr) {}
  ~PolicyAck() override;
  explicit PROTOBUF_CONSTEXPR PolicyAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PolicyAck(const PolicyAck& from);
  PolicyAck(PolicyAck&& from) noexcept
    : PolicyAck() {
    *this = ::std::move(from);
  }

  inline PolicyAck& operator=(const PolicyAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline PolicyAck& operator=(PolicyAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PolicyAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const PolicyAck* internal_default_instance() {
    return reinterpret_cast<const PolicyAck*>(
               &_PolicyAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(PolicyAck& a, PolicyAck& b) {
    a.Swap(&b);
  }
  inline void Swap(PolicyAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PolicyAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PolicyAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PolicyAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PolicyAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PolicyAck& from) {
    PolicyAck::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PolicyAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ddrl.comm.PolicyAck";
  }
  protected:
  explicit PolicyAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWorkerIdFieldNumber = 1,
    kVersionFieldNumber = 2,
    kReceivedUnixMsFieldNumber = 3,
  };
  // string worker_id = 1;
  void clear_worker_id();
  const std::string& worker_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_worker_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_worker_id();
  PROTOBUF_NODISCARD std::string* release_worker_id();
  void set_allocated_worker_id(std::string* worker_id);
  private:
  const std::string& _internal_worker_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_worker_id(const std::string& value);
  std::string* _internal_mutable_worker_id();
  public:

  // uint64 version = 2;
  void clear_version();
  uint64_t version() const;
  void set_version(uint64_t value);
  private:
  uint64_t _internal_version() const;
  void _internal_set_version(uint64_t value);
  public:

  // uint64 received_unix_ms = 3;
  void clear_received_unix_ms();
  uint64_t received_unix_ms() const;
  void set_received_unix_ms(uint64_t value);
  private:
  uint64_t _internal_received_unix_ms() const;
  void _internal_set_received_unix_ms(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:ddrl.comm.PolicyAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr worker_id_;
    uint64_t version_;
    uint64_t received_unix_ms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_policy_2eproto;
};
// -------------------------------------------------------------------

class PolicyStreamRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ddrl.comm.PolicyStreamRequest) */ {
 public:
  inline PolicyStreamRequest() : PolicyStreamRequest(nullptr) {}
  ~PolicyStreamRequest() override;
  explicit PROTOBUF_CONSTEXPR PolicyStreamRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PolicyStreamRequest(const PolicyStreamRequest& from);
  PolicyStreamRequest(PolicyStreamRequest&& from) noexcept
    : PolicyStreamRequest() {
    *this = ::std::move(from);
  }

  inline PolicyStreamRequest& operator=(const PolicyStreamRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PolicyStreamRequest& operator=(PolicyStreamRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PolicyStreamRequest& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kSubscribe = 1,
    kAck = 2,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const PolicyStreamRequest* internal_default_instance() {
    return reinterpret_cast<const PolicyStreamRequest*>(
               &_PolicyStreamRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(PolicyStreamRequest& a, PolicyStreamRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PolicyStreamRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PolicyStreamRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PolicyStreamRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PolicyStreamRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PolicyStreamRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PolicyStreamRequest& from) {
    PolicyStreamRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PolicyStreamRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ddrl.comm.PolicyStreamRequest";
  }
  protected:
  explicit PolicyStreamRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSubscribeFieldNumber = 1,
    kAckFieldNumber = 2,
  };
  // .ddrl.comm.PolicySubscription subscribe = 1;
  bool has_subscribe() const;
  private:
  bool _internal_has_subscribe() const;
  public:
  void clear_subscribe();
  const ::ddrl::comm::PolicySubscription& subscribe() const;
  PROTOBUF_NODISCARD ::ddrl::comm::PolicySubscription* release_subscribe();
  ::ddrl::comm::PolicySubscription* mutable_subscribe();
  void set_allocated_subscribe(::ddrl::comm::PolicySubscription* subscribe);
  private:
  const ::ddrl::comm::PolicySubscription& _internal_subscribe() const;
  ::ddrl::comm::PolicySubscription* _internal_mutable_subscribe();
  public:
  void unsafe_arena_set_allocated_subscribe(
      ::ddrl::comm::PolicySubscription* subscribe);
  ::ddrl::comm::PolicySubscription* unsafe_arena_release_subscribe();

  // .ddrl.comm.PolicyAck ack = 2;
  bool has_ack() const;
  private:
  bool _internal_has_ack() const;
  public:
  void clear_ack();
  const ::ddrl::comm::PolicyAck& ack() const;
  PROTOBUF_NODISCARD ::ddrl::comm::PolicyAck* release_ack();
  ::ddrl::comm::PolicyAck* mutable_ack();
  void set_allocated_ack(::ddrl::comm::PolicyAck* ack);
  private:
  const ::ddrl::comm::PolicyAck& _internal_ack() const;
  ::ddrl::comm::PolicyAck* _internal_mutable_ack();
  public:
  void unsafe_arena_set_allocated_ack(
      ::ddrl::comm::PolicyAck* ack);
  ::ddrl::comm::PolicyAck* unsafe_arena_release_ack();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:ddrl.comm.PolicyStreamRequest)
 private:
  class _Internal;
  void set_has_subscribe();
  void set_has_ack();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::ddrl::comm::PolicySubscription* subscribe_;
      ::ddrl::comm::PolicyAck* ack_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_policy_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PolicyTensor

// string name = 1;
inline void PolicyTensor::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& PolicyTensor::name() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyTensor.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PolicyTensor::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicyTensor.name)
}
inline std::string* PolicyTensor::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:ddrl.comm.PolicyTensor.name)
  return _s;
}
inline const std::string& PolicyTensor::_internal_name() const {
  return _impl_.name_.Get();
}
inline void PolicyTensor::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* PolicyTensor::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* PolicyTensor::release_name() {
  // @@protoc_insertion_point(field_release:ddrl.comm.PolicyTensor.name)
  return _impl_.name_.Release();
}
inline void PolicyTensor::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ddrl.comm.PolicyTensor.name)
}

// repeated int32 shape = 2;
inline int PolicyTensor::_internal_shape_size() const {
  return _impl_.shape_.size();
}
inline int PolicyTensor::shape_size() const {
  return _internal_shape_size();
}
inline void PolicyTensor::clear_shape() {
  _impl_.shape_.Clear();
}
inline int32_t PolicyTensor::_internal_shape(int index) const {
  return _impl_.shape_.Get(index);
}
inline int32_t PolicyTensor::shape(int index) const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyTensor.shape)
  return _internal_shape(index);
}
inline void PolicyTensor::set_shape(int index, int32_t value) {
  _impl_.shape_.Set(index, value);
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicyTensor.shape)
}
inline void PolicyTensor::_internal_add_shape(int32_t value) {
  _impl_.shape_.Add(value);
}
inline void PolicyTensor::add_shape(int32_t value) {
  _internal_add_shape(value);
  // @@protoc_insertion_point(field_add:ddrl.comm.PolicyTensor.shape)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
PolicyTensor::_internal_shape() const {
  return _impl_.shape_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
PolicyTensor::shape() const {
  // @@protoc_insertion_point(field_list:ddrl.comm.PolicyTensor.shape)
  return _internal_shape();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
PolicyTensor::_internal_mutable_shape() {
  return &_impl_.shape_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
PolicyTensor::mutable_shape() {
  // @@protoc_insertion_point(field_mutable_list:ddrl.comm.PolicyTensor.shape)
  return _internal_mutable_shape();
}

// bytes data = 3;
inline void PolicyTensor::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& PolicyTensor::data() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyTensor.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PolicyTensor::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicyTensor.data)
}
inline std::string* PolicyTensor::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:ddrl.comm.PolicyTensor.data)
  return _s;
}
inline const std::string& PolicyTensor::_internal_data() const {
  return _impl_.data_.Get();
}
inline void PolicyTensor::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* PolicyTensor::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* PolicyTensor::release_data() {
  // @@protoc_insertion_point(field_release:ddrl.comm.PolicyTensor.data)
  return _impl_.data_.Release();
}
inline void PolicyTensor::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ddrl.comm.PolicyTensor.data)
}

// string dtype = 4;
inline void PolicyTensor::clear_dtype() {
  _impl_.dtype_.ClearToEmpty();
}
inline const std::string& PolicyTensor::dtype() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyTensor.dtype)
  return _internal_dtype();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PolicyTensor::set_dtype(ArgT0&& arg0, ArgT... args) {
 
 _impl_.dtype_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicyTensor.dtype)
}
inline std::string* PolicyTensor::mutable_dtype() {
  std::string* _s = _internal_mutable_dtype();
  // @@protoc_insertion_point(field_mutable:ddrl.comm.PolicyTensor.dtype)
  return _s;
}
inline const std::string& PolicyTensor::_internal_dtype() const {
  return _impl_.dtype_.Get();
}
inline void PolicyTensor::_internal_set_dtype(const std::string& value) {
  
  _impl_.dtype_.Set(value, GetArenaForAllocation());
}
inline std::string* PolicyTensor::_internal_mutable_dtype() {
  
  return _impl_.dtype_.Mutable(GetArenaForAllocation());
}
inline std::string* PolicyTensor::release_dtype() {
  // @@protoc_insertion_point(field_release:ddrl.comm.PolicyTensor.dtype)
  return _impl_.dtype_.Release();
}
inline void PolicyTensor::set_allocated_dtype(std::string* dtype) {
  if (dtype != nullptr) {
    
  } else {
    
  }
  _impl_.dtype_.SetAllocated(dtype, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dtype_.IsDefault()) {
    _impl_.dtype_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ddrl.comm.PolicyTensor.dtype)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// PolicyPush

// uint64 version = 1;
inline void PolicyPush::clear_version() {
  _impl_.version_ = uint64_t{0u};
}
inline uint64_t PolicyPush::_internal_version() const {
  return _impl_.version_;
}
inline uint64_t PolicyPush::version() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyPush.version)
  return _internal_version();
}
inline void PolicyPush::_internal_set_version(uint64_t value) {
  
  _impl_.version_ = value;
}
inline void PolicyPush::set_version(uint64_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicyPush.version)
}

// repeated .ddrl.comm.PolicyTensor tensors = 2 [deprecated = true];
inline int PolicyPush::_internal_tensors_size() const {
  return _impl_.tensors_.size();
}
inline int PolicyPush::tensors_size() const {
  return _internal_tensors_size();
}
inline void PolicyPush::clear_tensors() {
  _impl_.tensors_.Clear();
}
inline ::ddrl::comm::PolicyTensor* PolicyPush::mutable_tensors(int index) {
  // @@protoc_insertion_point(field_mutable:ddrl.comm.PolicyPush.tensors)
  return _impl_.tensors_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ddrl::comm::PolicyTensor >*
PolicyPush::mutable_tensors() {
  // @@protoc_insertion_point(field_mutable_list:ddrl.comm.PolicyPush.tensors)
  return &_impl_.tensors_;
}
inline const ::ddrl::comm::PolicyTensor& PolicyPush::_internal_tensors(int index) const {
  return _impl_.tensors_.Get(index);
}
inline const ::ddrl::comm::PolicyTensor& PolicyPush::tensors(int index) const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyPush.tensors)
  return _internal_tensors(index);
}
inline ::ddrl::comm::PolicyTensor* PolicyPush::_internal_add_tensors() {
  return _impl_.tensors_.Add();
}
inline ::ddrl::comm::PolicyTensor* PolicyPush::add_tensors() {
  ::ddrl::comm::PolicyTensor* _add = _internal_add_tensors();
  // @@protoc_insertion_point(field_add:ddrl.comm.PolicyPush.tensors)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ddrl::comm::PolicyTensor >&
PolicyPush::tensors() const {
  // @@protoc_insertion_point(field_list:ddrl.comm.PolicyPush.tensors)
  return _impl_.tensors_;
}

// map<string, double> scalars = 3 [deprecated = true];
inline int PolicyPush::_internal_scalars_size() const {
  return _impl_.scalars_.size();
}
inline int PolicyPush::scalars_size() const {
  return _internal_scalars_size();
}
inline void PolicyPush::clear_scalars() {
  _impl_.scalars_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >&
PolicyPush::_internal_scalars() const {
  return _impl_.scalars_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >&
PolicyPush::scalars() const {
  // @@protoc_insertion_point(field_map:ddrl.comm.PolicyPush.scalars)
  return _internal_scalars();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >*
PolicyPush::_internal_mutable_scalars() {
  return _impl_.scalars_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, double >*
PolicyPush::mutable_scalars() {
  // @@protoc_insertion_point(field_mutable_map:ddrl.comm.PolicyPush.scalars)
  return _internal_mutable_scalars();
}

// bytes metadata = 4 [deprecated = true];
inline void PolicyPush::clear_metadata() {
  _impl_.metadata_.ClearToEmpty();
}
inline const std::string& PolicyPush::metadata() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyPush.metadata)
  return _internal_metadata();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PolicyPush::set_metadata(ArgT0&& arg0, ArgT... args) {
 
 _impl_.metadata_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicyPush.metadata)
}
inline std::string* PolicyPush::mutable_metadata() {
  std::string* _s = _internal_mutable_metadata();
  // @@protoc_insertion_point(field_mutable:ddrl.comm.PolicyPush.metadata)
  return _s;
}
inline const std::string& PolicyPush::_internal_metadata() const {
  return _impl_.metadata_.Get();
}
inline void PolicyPush::_internal_set_metadata(const std::string& value) {
  
  _impl_.metadata_.Set(value, GetArenaForAllocation());
}
inline std::string* PolicyPush::_internal_mutable_metadata() {
  
  return _impl_.metadata_.Mutable(GetArenaForAllocation());
}
inline std::string* PolicyPush::release_metadata() {
  // @@protoc_insertion_point(field_release:ddrl.comm.PolicyPush.metadata)
  return _impl_.metadata_.Release();
}
inline void PolicyPush::set_allocated_metadata(std::string* metadata) {
  if (metadata != nullptr) {
    
  } else {
    
  }
  _impl_.metadata_.SetAllocated(metadata, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.metadata_.IsDefault()) {
    _impl_.metadata_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ddrl.comm.PolicyPush.metadata)
}

// bytes onnx_model = 5;
inline void PolicyPush::clear_onnx_model() {
  _impl_.onnx_model_.ClearToEmpty();
}
inline const std::string& PolicyPush::onnx_model() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyPush.onnx_model)
  return _internal_onnx_model();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PolicyPush::set_onnx_model(ArgT0&& arg0, ArgT... args) {
 
 _impl_.onnx_model_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicyPush.onnx_model)
}
inline std::string* PolicyPush::mutable_onnx_model() {
  std::string* _s = _internal_mutable_onnx_model();
  // @@protoc_insertion_point(field_mutable:ddrl.comm.PolicyPush.onnx_model)
  return _s;
}
inline const std::string& PolicyPush::_internal_onnx_model() const {
  return _impl_.onnx_model_.Get();
}
inline void PolicyPush::_internal_set_onnx_model(const std::string& value) {
  
  _impl_.onnx_model_.Set(value, GetArenaForAllocation());
}
inline std::string* PolicyPush::_internal_mutable_onnx_model() {
  
  return _impl_.onnx_model_.Mutable(GetArenaForAllocation());
}
inline std::string* PolicyPush::release_onnx_model() {
  // @@protoc_insertion_point(field_release:ddrl.comm.PolicyPush.onnx_model)
  return _impl_.onnx_model_.Release();
}
inline void PolicyPush::set_allocated_onnx_model(std::string* onnx_model) {
  if (onnx_model != nullptr) {
    
  } else {
    
  }
  _impl_.onnx_model_.SetAllocated(onnx_model, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.onnx_model_.IsDefault()) {
    _impl_.onnx_model_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ddrl.comm.PolicyPush.onnx_model)
}

// -------------------------------------------------------------------

// PolicySubscription

// string worker_id = 1;
inline void PolicySubscription::clear_worker_id() {
  _impl_.worker_id_.ClearToEmpty();
}
inline const std::string& PolicySubscription::worker_id() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicySubscription.worker_id)
  return _internal_worker_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PolicySubscription::set_worker_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.worker_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicySubscription.worker_id)
}
inline std::string* PolicySubscription::mutable_worker_id() {
  std::string* _s = _internal_mutable_worker_id();
  // @@protoc_insertion_point(field_mutable:ddrl.comm.PolicySubscription.worker_id)
  return _s;
}
inline const std::string& PolicySubscription::_internal_worker_id() const {
  return _impl_.worker_id_.Get();
}
inline void PolicySubscription::_internal_set_worker_id(const std::string& value) {
  
  _impl_.worker_id_.Set(value, GetArenaForAllocation());
}
inline std::string* PolicySubscription::_internal_mutable_worker_id() {
  
  return _impl_.worker_id_.Mutable(GetArenaForAllocation());
}
inline std::string* PolicySubscription::release_worker_id() {
  // @@protoc_insertion_point(field_release:ddrl.comm.PolicySubscription.worker_id)
  return _impl_.worker_id_.Release();
}
inline void PolicySubscription::set_allocated_worker_id(std::string* worker_id) {
  if (worker_id != nullptr) {
    
  } else {
    
  }
  _impl_.worker_id_.SetAllocated(worker_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.worker_id_.IsDefault()) {
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ddrl.comm.PolicySubscription.worker_id)
}

// string session_token = 2;
inline void PolicySubscription::clear_session_token() {
  _impl_.session_token_.ClearToEmpty();
}
inline const std::string& PolicySubscription::session_token() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicySubscription.session_token)
  return _internal_session_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PolicySubscription::set_session_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.session_token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicySubscription.session_token)
}
inline std::string* PolicySubscription::mutable_session_token() {
  std::string* _s = _internal_mutable_session_token();
  // @@protoc_insertion_point(field_mutable:ddrl.comm.PolicySubscription.session_token)
  return _s;
}
inline const std::string& PolicySubscription::_internal_session_token() const {
  return _impl_.session_token_.Get();
}
inline void PolicySubscription::_internal_set_session_token(const std::string& value) {
  
  _impl_.session_token_.Set(value, GetArenaForAllocation());
}
inline std::string* PolicySubscription::_internal_mutable_session_token() {
  
  return _impl_.session_token_.Mutable(GetArenaForAllocation());
}
inline std::string* PolicySubscription::release_session_token() {
  // @@protoc_insertion_point(field_release:ddrl.comm.PolicySubscription.session_token)
  return _impl_.session_token_.Release();
}
inline void PolicySubscription::set_allocated_session_token(std::string* session_token) {
  if (session_token != nullptr) {
    
  } else {
    
  }
  _impl_.session_token_.SetAllocated(session_token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_token_.IsDefault()) {
    _impl_.session_token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ddrl.comm.PolicySubscription.session_token)
}

// uint64 last_version = 3;
inline void PolicySubscription::clear_last_version() {
  _impl_.last_version_ = uint64_t{0u};
}
inline uint64_t PolicySubscription::_internal_last_version() const {
  return _impl_.last_version_;
}
inline uint64_t PolicySubscription::last_version() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicySubscription.last_version)
  return _internal_last_version();
}
inline void PolicySubscription::_internal_set_last_version(uint64_t value) {
  
  _impl_.last_version_ = value;
}
inline void PolicySubscription::set_last_version(uint64_t value) {
  _internal_set_last_version(value);
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicySubscription.last_version)
}

// -------------------------------------------------------------------

// PolicyAck

// string worker_id = 1;
inline void PolicyAck::clear_worker_id() {
  _impl_.worker_id_.ClearToEmpty();
}
inline const std::string& PolicyAck::worker_id() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyAck.worker_id)
  return _internal_worker_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PolicyAck::set_worker_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.worker_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicyAck.worker_id)
}
inline std::string* PolicyAck::mutable_worker_id() {
  std::string* _s = _internal_mutable_worker_id();
  // @@protoc_insertion_point(field_mutable:ddrl.comm.PolicyAck.worker_id)
  return _s;
}
inline const std::string& PolicyAck::_internal_worker_id() const {
  return _impl_.worker_id_.Get();
}
inline void PolicyAck::_internal_set_worker_id(const std::string& value) {
  
  _impl_.worker_id_.Set(value, GetArenaForAllocation());
}
inline std::string* PolicyAck::_internal_mutable_worker_id() {
  
  return _impl_.worker_id_.Mutable(GetArenaForAllocation());
}
inline std::string* PolicyAck::release_worker_id() {
  // @@protoc_insertion_point(field_release:ddrl.comm.PolicyAck.worker_id)
  return _impl_.worker_id_.Release();
}
inline void PolicyAck::set_allocated_worker_id(std::string* worker_id) {
  if (worker_id != nullptr) {
    
  } else {
    
  }
  _impl_.worker_id_.SetAllocated(worker_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.worker_id_.IsDefault()) {
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ddrl.comm.PolicyAck.worker_id)
}

// uint64 version = 2;
inline void PolicyAck::clear_version() {
  _impl_.version_ = uint64_t{0u};
}
inline uint64_t PolicyAck::_internal_version() const {
  return _impl_.version_;
}
inline uint64_t PolicyAck::version() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyAck.version)
  return _internal_version();
}
inline void PolicyAck::_internal_set_version(uint64_t value) {
  
  _impl_.version_ = value;
}
inline void PolicyAck::set_version(uint64_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicyAck.version)
}

// uint64 received_unix_ms = 3;
inline void PolicyAck::clear_received_unix_ms() {
  _impl_.received_unix_ms_ = uint64_t{0u};
}
inline uint64_t PolicyAck::_internal_received_unix_ms() const {
  return _impl_.received_unix_ms_;
}
inline uint64_t PolicyAck::received_unix_ms() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyAck.received_unix_ms)
  return _internal_received_unix_ms();
}
inline void PolicyAck::_internal_set_received_unix_ms(uint64_t value) {
  
  _impl_.received_unix_ms_ = value;
}
inline void PolicyAck::set_received_unix_ms(uint64_t value) {
  _internal_set_received_unix_ms(value);
  // @@protoc_insertion_point(field_set:ddrl.comm.PolicyAck.received_unix_ms)
}

// -------------------------------------------------------------------

// PolicyStreamRequest

// .ddrl.comm.PolicySubscription subscribe = 1;
inline bool PolicyStreamRequest::_internal_has_subscribe() const {
  return payload_case() == kSubscribe;
}
inline bool PolicyStreamRequest::has_subscribe() const {
  return _internal_has_subscribe();
}
inline void PolicyStreamRequest::set_has_subscribe() {
  _impl_._oneof_case_[0] = kSubscribe;
}
inline void PolicyStreamRequest::clear_subscribe() {
  if (_internal_has_subscribe()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.subscribe_;
    }
    clear_has_payload();
  }
}
inline ::ddrl::comm::PolicySubscription* PolicyStreamRequest::release_subscribe() {
  // @@protoc_insertion_point(field_release:ddrl.comm.PolicyStreamRequest.subscribe)
  if (_internal_has_subscribe()) {
    clear_has_payload();
    ::ddrl::comm::PolicySubscription* temp = _impl_.payload_.subscribe_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.subscribe_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::ddrl::comm::PolicySubscription& PolicyStreamRequest::_internal_subscribe() const {
  return _internal_has_subscribe()
      ? *_impl_.payload_.subscribe_
      : reinterpret_cast< ::ddrl::comm::PolicySubscription&>(::ddrl::comm::_PolicySubscription_default_instance_);
}
inline const ::ddrl::comm::PolicySubscription& PolicyStreamRequest::subscribe() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyStreamRequest.subscribe)
  return _internal_subscribe();
}
inline ::ddrl::comm::PolicySubscription* PolicyStreamRequest::unsafe_arena_release_subscribe() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ddrl.comm.PolicyStreamRequest.subscribe)
  if (_internal_has_subscribe()) {
    clear_has_payload();
    ::ddrl::comm::PolicySubscription* temp = _impl_.payload_.subscribe_;
    _impl_.payload_.subscribe_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PolicyStreamRequest::unsafe_arena_set_allocated_subscribe(::ddrl::comm::PolicySubscription* subscribe) {
  clear_payload();
  if (subscribe) {
    set_has_subscribe();
    _impl_.payload_.subscribe_ = subscribe;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ddrl.comm.PolicyStreamRequest.subscribe)
}
inline ::ddrl::comm::PolicySubscription* PolicyStreamRequest::_internal_mutable_subscribe() {
  if (!_internal_has_subscribe()) {
    clear_payload();
    set_has_subscribe();
    _impl_.payload_.subscribe_ = CreateMaybeMessage< ::ddrl::comm::PolicySubscription >(GetArenaForAllocation());
  }
  return _impl_.payload_.subscribe_;
}
inline ::ddrl::comm::PolicySubscription* PolicyStreamRequest::mutable_subscribe() {
  ::ddrl::comm::PolicySubscription* _msg = _internal_mutable_subscribe();
  // @@protoc_insertion_point(field_mutable:ddrl.comm.PolicyStreamRequest.subscribe)
  return _msg;
}

// .ddrl.comm.PolicyAck ack = 2;
inline bool PolicyStreamRequest::_internal_has_ack() const {
  return payload_case() == kAck;
}
inline bool PolicyStreamRequest::has_ack() const {
  return _internal_has_ack();
}
inline void PolicyStreamRequest::set_has_ack() {
  _impl_._oneof_case_[0] = kAck;
}
inline void PolicyStreamRequest::clear_ack() {
  if (_internal_has_ack()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.ack_;
    }
    clear_has_payload();
  }
}
inline ::ddrl::comm::PolicyAck* PolicyStreamRequest::release_ack() {
  // @@protoc_insertion_point(field_release:ddrl.comm.PolicyStreamRequest.ack)
  if (_internal_has_ack()) {
    clear_has_payload();
    ::ddrl::comm::PolicyAck* temp = _impl_.payload_.ack_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.ack_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::ddrl::comm::PolicyAck& PolicyStreamRequest::_internal_ack() const {
  return _internal_has_ack()
      ? *_impl_.payload_.ack_
      : reinterpret_cast< ::ddrl::comm::PolicyAck&>(::ddrl::comm::_PolicyAck_default_instance_);
}
inline const ::ddrl::comm::PolicyAck& PolicyStreamRequest::ack() const {
  // @@protoc_insertion_point(field_get:ddrl.comm.PolicyStreamRequest.ack)
  return _internal_ack();
}
inline ::ddrl::comm::PolicyAck* PolicyStreamRequest::unsafe_arena_release_ack() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ddrl.comm.PolicyStreamRequest.ack)
  if (_internal_has_ack()) {
    clear_has_payload();
    ::ddrl::comm::PolicyAck* temp = _impl_.payload_.ack_;
    _impl_.payload_.ack_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PolicyStreamRequest::unsafe_arena_set_allocated_ack(::ddrl::comm::PolicyAck* ack) {
  clear_payload();
  if (ack) {
    set_has_ack();
    _impl_.payload_.ack_ = ack;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ddrl.comm.PolicyStreamRequest.ack)
}
inline ::ddrl::comm::PolicyAck* PolicyStreamRequest::_internal_mutable_ack() {
  if (!_internal_has_ack()) {
    clear_payload();
    set_has_ack();
    _impl_.payload_.ack_ = CreateMaybeMessage< ::ddrl::comm::PolicyAck >(GetArenaForAllocation());
  }
  return _impl_.payload_.ack_;
}
inline ::ddrl::comm::PolicyAck* PolicyStreamRequest::mutable_ack() {
  ::ddrl::comm::PolicyAck* _msg = _internal_mutable_ack();
  // @@protoc_insertion_point(field_mutable:ddrl.comm.PolicyStreamRequest.ack)
  return _msg;
}

inline bool PolicyStreamRequest::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void PolicyStreamRequest::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline PolicyStreamRequest::PayloadCase PolicyStreamRequest::payload_case() const {
  return PolicyStreamRequest::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm
}  // namespace ddrl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_policy_2eproto
