// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: policy.proto

#include "policy.pb.h"
#include "policy.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ddrl {
namespace comm {

static const char* PolicyService_method_names[] = {
  "/ddrl.comm.PolicyService/StreamPolicyUpdates",
};

std::unique_ptr< PolicyService::Stub> PolicyService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PolicyService::Stub> stub(new PolicyService::Stub(channel, options));
  return stub;
}

PolicyService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamPolicyUpdates_(PolicyService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>* PolicyService::Stub::StreamPolicyUpdatesRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>::Create(channel_.get(), rpcmethod_StreamPolicyUpdates_, context);
}

void PolicyService::Stub::async::StreamPolicyUpdates(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ddrl::comm::PolicyStreamRequest,::ddrl::comm::PolicyPush>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::ddrl::comm::PolicyStreamRequest,::ddrl::comm::PolicyPush>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamPolicyUpdates_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>* PolicyService::Stub::AsyncStreamPolicyUpdatesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>::Create(channel_.get(), cq, rpcmethod_StreamPolicyUpdates_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>* PolicyService::Stub::PrepareAsyncStreamPolicyUpdatesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>::Create(channel_.get(), cq, rpcmethod_StreamPolicyUpdates_, context, false, nullptr);
}

PolicyService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PolicyService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< PolicyService::Service, ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>(
          [](PolicyService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::ddrl::comm::PolicyPush,
             ::ddrl::comm::PolicyStreamRequest>* stream) {
               return service->StreamPolicyUpdates(ctx, stream);
             }, this)));
}

PolicyService::Service::~Service() {
}

::grpc::Status PolicyService::Service::StreamPolicyUpdates(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ddrl::comm::PolicyPush, ::ddrl::comm::PolicyStreamRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ddrl
}  // namespace comm

