// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy.proto

#include "policy.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ddrl {
namespace comm {
PROTOBUF_CONSTEXPR PolicyTensor::PolicyTensor(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.shape_)*/{}
  , /*decltype(_impl_._shape_cached_byte_size_)*/{0}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.dtype_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PolicyTensorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PolicyTensorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PolicyTensorDefaultTypeInternal() {}
  union {
    PolicyTensor _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PolicyTensorDefaultTypeInternal _PolicyTensor_default_instance_;
PROTOBUF_CONSTEXPR PolicyPush_ScalarsEntry_DoNotUse::PolicyPush_ScalarsEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct PolicyPush_ScalarsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PolicyPush_ScalarsEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PolicyPush_ScalarsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    PolicyPush_ScalarsEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PolicyPush_ScalarsEntry_DoNotUseDefaultTypeInternal _PolicyPush_ScalarsEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR PolicyPush::PolicyPush(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.tensors_)*/{}
  , /*decltype(_impl_.scalars_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.metadata_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.onnx_model_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.version_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PolicyPushDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PolicyPushDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PolicyPushDefaultTypeInternal() {}
  union {
    PolicyPush _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PolicyPushDefaultTypeInternal _PolicyPush_default_instance_;
PROTOBUF_CONSTEXPR PolicySubscription::PolicySubscription(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.worker_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.session_token_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.last_version_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PolicySubscriptionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PolicySubscriptionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PolicySubscriptionDefaultTypeInternal() {}
  union {
    PolicySubscription _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PolicySubscriptionDefaultTypeInternal _PolicySubscription_default_instance_;
PROTOBUF_CONSTEXPR PolicyAck::PolicyAck(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.worker_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.version_)*/uint64_t{0u}
  , /*decltype(_impl_.received_unix_ms_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PolicyAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PolicyAckDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PolicyAckDefaultTypeInternal() {}
  union {
    PolicyAck _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PolicyAckDefaultTypeInternal _PolicyAck_default_instance_;
PROTOBUF_CONSTEXPR PolicyStreamRequest::PolicyStreamRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.payload_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct PolicyStreamRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PolicyStreamRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PolicyStreamRequestDefaultTypeInternal() {}
  union {
    PolicyStreamRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PolicyStreamRequestDefaultTypeInternal _PolicyStreamRequest_default_instance_;
}  // namespace comm
}  // namespace ddrl
static ::_pb::Metadata file_level_metadata_policy_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_policy_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_policy_2eproto = nullptr;

const uint32_t TableStruct_policy_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyTensor, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyTensor, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyTensor, _impl_.shape_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyTensor, _impl_.data_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyTensor, _impl_.dtype_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyPush_ScalarsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyPush_ScalarsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyPush_ScalarsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyPush_ScalarsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyPush, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyPush, _impl_.version_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyPush, _impl_.tensors_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyPush, _impl_.scalars_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyPush, _impl_.metadata_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyPush, _impl_.onnx_model_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicySubscription, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicySubscription, _impl_.worker_id_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicySubscription, _impl_.session_token_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicySubscription, _impl_.last_version_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyAck, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyAck, _impl_.worker_id_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyAck, _impl_.version_),
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyAck, _impl_.received_unix_ms_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyStreamRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyStreamRequest, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::ddrl::comm::PolicyStreamRequest, _impl_.payload_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ddrl::comm::PolicyTensor)},
  { 10, 18, -1, sizeof(::ddrl::comm::PolicyPush_ScalarsEntry_DoNotUse)},
  { 20, -1, -1, sizeof(::ddrl::comm::PolicyPush)},
  { 31, -1, -1, sizeof(::ddrl::comm::PolicySubscription)},
  { 40, -1, -1, sizeof(::ddrl::comm::PolicyAck)},
  { 49, -1, -1, sizeof(::ddrl::comm::PolicyStreamRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ddrl::comm::_PolicyTensor_default_instance_._instance,
  &::ddrl::comm::_PolicyPush_ScalarsEntry_DoNotUse_default_instance_._instance,
  &::ddrl::comm::_PolicyPush_default_instance_._instance,
  &::ddrl::comm::_PolicySubscription_default_instance_._instance,
  &::ddrl::comm::_PolicyAck_default_instance_._instance,
  &::ddrl::comm::_PolicyStreamRequest_default_instance_._instance,
};

const char descriptor_table_protodef_policy_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014policy.proto\022\tddrl.comm\"H\n\014PolicyTenso"
  "r\022\014\n\004name\030\001 \001(\t\022\r\n\005shape\030\002 \003(\005\022\014\n\004data\030\003"
  " \001(\014\022\r\n\005dtype\030\004 \001(\t\"\336\001\n\nPolicyPush\022\017\n\007ve"
  "rsion\030\001 \001(\004\022,\n\007tensors\030\002 \003(\0132\027.ddrl.comm"
  ".PolicyTensorB\002\030\001\0227\n\007scalars\030\003 \003(\0132\".ddr"
  "l.comm.PolicyPush.ScalarsEntryB\002\030\001\022\024\n\010me"
  "tadata\030\004 \001(\014B\002\030\001\022\022\n\nonnx_model\030\005 \001(\014\032.\n\014"
  "ScalarsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\001"
  ":\0028\001\"T\n\022PolicySubscription\022\021\n\tworker_id\030"
  "\001 \001(\t\022\025\n\rsession_token\030\002 \001(\t\022\024\n\014last_ver"
  "sion\030\003 \001(\004\"I\n\tPolicyAck\022\021\n\tworker_id\030\001 \001"
  "(\t\022\017\n\007version\030\002 \001(\004\022\030\n\020received_unix_ms\030"
  "\003 \001(\004\"y\n\023PolicyStreamRequest\0222\n\tsubscrib"
  "e\030\001 \001(\0132\035.ddrl.comm.PolicySubscriptionH\000"
  "\022#\n\003ack\030\002 \001(\0132\024.ddrl.comm.PolicyAckH\000B\t\n"
  "\007payload2a\n\rPolicyService\022P\n\023StreamPolic"
  "yUpdates\022\036.ddrl.comm.PolicyStreamRequest"
  "\032\025.ddrl.comm.PolicyPush(\0010\001BW\n\014ai.ddrl.c"
  "ommP\001Z9github.com/ddrl/collision-avoidan"
  "ce/comm/gen/go/ddrl/comm\252\002\tDdrl.Commb\006pr"
  "oto3"
  ;
static ::_pbi::once_flag descriptor_table_policy_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_policy_2eproto = {
    false, false, 804, descriptor_table_protodef_policy_2eproto,
    "policy.proto",
    &descriptor_table_policy_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_policy_2eproto::offsets,
    file_level_metadata_policy_2eproto, file_level_enum_descriptors_policy_2eproto,
    file_level_service_descriptors_policy_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_policy_2eproto_getter() {
  return &descriptor_table_policy_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_policy_2eproto(&descriptor_table_policy_2eproto);
namespace ddrl {
namespace comm {

// ===================================================================

class PolicyTensor::_Internal {
 public:
};

PolicyTensor::PolicyTensor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ddrl.comm.PolicyTensor)
}
PolicyTensor::PolicyTensor(const PolicyTensor& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PolicyTensor* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.shape_){from._impl_.shape_}
    , /*decltype(_impl_._shape_cached_byte_size_)*/{0}
    , decltype(_impl_.name_){}
    , decltype(_impl_.data_){}
    , decltype(_impl_.dtype_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  _impl_.dtype_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dtype_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_dtype().empty()) {
    _this->_impl_.dtype_.Set(from._internal_dtype(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ddrl.comm.PolicyTensor)
}

inline void PolicyTensor::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.shape_){arena}
    , /*decltype(_impl_._shape_cached_byte_size_)*/{0}
    , decltype(_impl_.name_){}
    , decltype(_impl_.data_){}
    , decltype(_impl_.dtype_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.dtype_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dtype_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PolicyTensor::~PolicyTensor() {
  // @@protoc_insertion_point(destructor:ddrl.comm.PolicyTensor)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PolicyTensor::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.shape_.~RepeatedField();
  _impl_.name_.Destroy();
  _impl_.data_.Destroy();
  _impl_.dtype_.Destroy();
}

void PolicyTensor::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PolicyTensor::Clear() {
// @@protoc_insertion_point(message_clear_start:ddrl.comm.PolicyTensor)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.shape_.Clear();
  _impl_.name_.ClearToEmpty();
  _impl_.data_.ClearToEmpty();
  _impl_.dtype_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PolicyTensor::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ddrl.comm.PolicyTensor.name"));
        } else
          goto handle_unusual;
        continue;
      // repeated int32 shape = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_shape(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_shape(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string dtype = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_dtype();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ddrl.comm.PolicyTensor.dtype"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PolicyTensor::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ddrl.comm.PolicyTensor)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ddrl.comm.PolicyTensor.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // repeated int32 shape = 2;
  {
    int byte_size = _impl_._shape_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          2, _internal_shape(), byte_size, target);
    }
  }

  // bytes data = 3;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_data(), target);
  }

  // string dtype = 4;
  if (!this->_internal_dtype().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_dtype().data(), static_cast<int>(this->_internal_dtype().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ddrl.comm.PolicyTensor.dtype");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_dtype(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ddrl.comm.PolicyTensor)
  return target;
}

size_t PolicyTensor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ddrl.comm.PolicyTensor)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 shape = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.shape_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._shape_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // bytes data = 3;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // string dtype = 4;
  if (!this->_internal_dtype().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_dtype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PolicyTensor::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PolicyTensor::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PolicyTensor::GetClassData() const { return &_class_data_; }


void PolicyTensor::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PolicyTensor*>(&to_msg);
  auto& from = static_cast<const PolicyTensor&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ddrl.comm.PolicyTensor)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.shape_.MergeFrom(from._impl_.shape_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (!from._internal_dtype().empty()) {
    _this->_internal_set_dtype(from._internal_dtype());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PolicyTensor::CopyFrom(const PolicyTensor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ddrl.comm.PolicyTensor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PolicyTensor::IsInitialized() const {
  return true;
}

void PolicyTensor::InternalSwap(PolicyTensor* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.shape_.InternalSwap(&other->_impl_.shape_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.dtype_, lhs_arena,
      &other->_impl_.dtype_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata PolicyTensor::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_policy_2eproto_getter, &descriptor_table_policy_2eproto_once,
      file_level_metadata_policy_2eproto[0]);
}

// ===================================================================

PolicyPush_ScalarsEntry_DoNotUse::PolicyPush_ScalarsEntry_DoNotUse() {}
PolicyPush_ScalarsEntry_DoNotUse::PolicyPush_ScalarsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void PolicyPush_ScalarsEntry_DoNotUse::MergeFrom(const PolicyPush_ScalarsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata PolicyPush_ScalarsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_policy_2eproto_getter, &descriptor_table_policy_2eproto_once,
      file_level_metadata_policy_2eproto[1]);
}

// ===================================================================

class PolicyPush::_Internal {
 public:
};

PolicyPush::PolicyPush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &PolicyPush::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:ddrl.comm.PolicyPush)
}
PolicyPush::PolicyPush(const PolicyPush& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PolicyPush* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.tensors_){from._impl_.tensors_}
    , /*decltype(_impl_.scalars_)*/{}
    , decltype(_impl_.metadata_){}
    , decltype(_impl_.onnx_model_){}
    , decltype(_impl_.version_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.scalars_.MergeFrom(from._impl_.scalars_);
  _impl_.metadata_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.metadata_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_metadata().empty()) {
    _this->_impl_.metadata_.Set(from._internal_metadata(), 
      _this->GetArenaForAllocation());
  }
  _impl_.onnx_model_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.onnx_model_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_onnx_model().empty()) {
    _this->_impl_.onnx_model_.Set(from._internal_onnx_model(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.version_ = from._impl_.version_;
  // @@protoc_insertion_point(copy_constructor:ddrl.comm.PolicyPush)
}

inline void PolicyPush::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.tensors_){arena}
    , /*decltype(_impl_.scalars_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.metadata_){}
    , decltype(_impl_.onnx_model_){}
    , decltype(_impl_.version_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.metadata_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.metadata_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.onnx_model_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.onnx_model_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PolicyPush::~PolicyPush() {
  // @@protoc_insertion_point(destructor:ddrl.comm.PolicyPush)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void PolicyPush::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.tensors_.~RepeatedPtrField();
  _impl_.scalars_.Destruct();
  _impl_.scalars_.~MapField();
  _impl_.metadata_.Destroy();
  _impl_.onnx_model_.Destroy();
}

void PolicyPush::ArenaDtor(void* object) {
  PolicyPush* _this = reinterpret_cast< PolicyPush* >(object);
  _this->_impl_.scalars_.Destruct();
}
void PolicyPush::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PolicyPush::Clear() {
// @@protoc_insertion_point(message_clear_start:ddrl.comm.PolicyPush)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.tensors_.Clear();
  _impl_.scalars_.Clear();
  _impl_.metadata_.ClearToEmpty();
  _impl_.onnx_model_.ClearToEmpty();
  _impl_.version_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PolicyPush::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .ddrl.comm.PolicyTensor tensors = 2 [deprecated = true];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_tensors(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // map<string, double> scalars = 3 [deprecated = true];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.scalars_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // bytes metadata = 4 [deprecated = true];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_metadata();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes onnx_model = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_onnx_model();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PolicyPush::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ddrl.comm.PolicyPush)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 version = 1;
  if (this->_internal_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_version(), target);
  }

  // repeated .ddrl.comm.PolicyTensor tensors = 2 [deprecated = true];
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_tensors_size()); i < n; i++) {
    const auto& repfield = this->_internal_tensors(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // map<string, double> scalars = 3 [deprecated = true];
  if (!this->_internal_scalars().empty()) {
    using MapType = ::_pb::Map<std::string, double>;
    using WireHelper = PolicyPush_ScalarsEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_scalars();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "ddrl.comm.PolicyPush.ScalarsEntry.key");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  // bytes metadata = 4 [deprecated = true];
  if (!this->_internal_metadata().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_metadata(), target);
  }

  // bytes onnx_model = 5;
  if (!this->_internal_onnx_model().empty()) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_onnx_model(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ddrl.comm.PolicyPush)
  return target;
}

size_t PolicyPush::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ddrl.comm.PolicyPush)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ddrl.comm.PolicyTensor tensors = 2 [deprecated = true];
  total_size += 1UL * this->_internal_tensors_size();
  for (const auto& msg : this->_impl_.tensors_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // map<string, double> scalars = 3 [deprecated = true];
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_scalars_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, double >::const_iterator
      it = this->_internal_scalars().begin();
      it != this->_internal_scalars().end(); ++it) {
    total_size += PolicyPush_ScalarsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // bytes metadata = 4 [deprecated = true];
  if (!this->_internal_metadata().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_metadata());
  }

  // bytes onnx_model = 5;
  if (!this->_internal_onnx_model().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_onnx_model());
  }

  // uint64 version = 1;
  if (this->_internal_version() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PolicyPush::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PolicyPush::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PolicyPush::GetClassData() const { return &_class_data_; }


void PolicyPush::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PolicyPush*>(&to_msg);
  auto& from = static_cast<const PolicyPush&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ddrl.comm.PolicyPush)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.tensors_.MergeFrom(from._impl_.tensors_);
  _this->_impl_.scalars_.MergeFrom(from._impl_.scalars_);
  if (!from._internal_metadata().empty()) {
    _this->_internal_set_metadata(from._internal_metadata());
  }
  if (!from._internal_onnx_model().empty()) {
    _this->_internal_set_onnx_model(from._internal_onnx_model());
  }
  if (from._internal_version() != 0) {
    _this->_internal_set_version(from._internal_version());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PolicyPush::CopyFrom(const PolicyPush& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ddrl.comm.PolicyPush)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PolicyPush::IsInitialized() const {
  return true;
}

void PolicyPush::InternalSwap(PolicyPush* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.tensors_.InternalSwap(&other->_impl_.tensors_);
  _impl_.scalars_.InternalSwap(&other->_impl_.scalars_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.metadata_, lhs_arena,
      &other->_impl_.metadata_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.onnx_model_, lhs_arena,
      &other->_impl_.onnx_model_, rhs_arena
  );
  swap(_impl_.version_, other->_impl_.version_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PolicyPush::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_policy_2eproto_getter, &descriptor_table_policy_2eproto_once,
      file_level_metadata_policy_2eproto[2]);
}

// ===================================================================

class PolicySubscription::_Internal {
 public:
};

PolicySubscription::PolicySubscription(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ddrl.comm.PolicySubscription)
}
PolicySubscription::PolicySubscription(const PolicySubscription& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PolicySubscription* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.worker_id_){}
    , decltype(_impl_.session_token_){}
    , decltype(_impl_.last_version_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_worker_id().empty()) {
    _this->_impl_.worker_id_.Set(from._internal_worker_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.session_token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_session_token().empty()) {
    _this->_impl_.session_token_.Set(from._internal_session_token(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.last_version_ = from._impl_.last_version_;
  // @@protoc_insertion_point(copy_constructor:ddrl.comm.PolicySubscription)
}

inline void PolicySubscription::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.worker_id_){}
    , decltype(_impl_.session_token_){}
    , decltype(_impl_.last_version_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.session_token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PolicySubscription::~PolicySubscription() {
  // @@protoc_insertion_point(destructor:ddrl.comm.PolicySubscription)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PolicySubscription::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.worker_id_.Destroy();
  _impl_.session_token_.Destroy();
}

void PolicySubscription::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PolicySubscription::Clear() {
// @@protoc_insertion_point(message_clear_start:ddrl.comm.PolicySubscription)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.worker_id_.ClearToEmpty();
  _impl_.session_token_.ClearToEmpty();
  _impl_.last_version_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PolicySubscription::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string worker_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_worker_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ddrl.comm.PolicySubscription.worker_id"));
        } else
          goto handle_unusual;
        continue;
      // string session_token = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_session_token();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ddrl.comm.PolicySubscription.session_token"));
        } else
          goto handle_unusual;
        continue;
      // uint64 last_version = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.last_version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PolicySubscription::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ddrl.comm.PolicySubscription)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string worker_id = 1;
  if (!this->_internal_worker_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_worker_id().data(), static_cast<int>(this->_internal_worker_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ddrl.comm.PolicySubscription.worker_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_worker_id(), target);
  }

  // string session_token = 2;
  if (!this->_internal_session_token().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_token().data(), static_cast<int>(this->_internal_session_token().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ddrl.comm.PolicySubscription.session_token");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_session_token(), target);
  }

  // uint64 last_version = 3;
  if (this->_internal_last_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_last_version(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ddrl.comm.PolicySubscription)
  return target;
}

size_t PolicySubscription::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ddrl.comm.PolicySubscription)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string worker_id = 1;
  if (!this->_internal_worker_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_worker_id());
  }

  // string session_token = 2;
  if (!this->_internal_session_token().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_token());
  }

  // uint64 last_version = 3;
  if (this->_internal_last_version() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_last_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PolicySubscription::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PolicySubscription::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PolicySubscription::GetClassData() const { return &_class_data_; }


void PolicySubscription::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PolicySubscription*>(&to_msg);
  auto& from = static_cast<const PolicySubscription&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ddrl.comm.PolicySubscription)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_worker_id().empty()) {
    _this->_internal_set_worker_id(from._internal_worker_id());
  }
  if (!from._internal_session_token().empty()) {
    _this->_internal_set_session_token(from._internal_session_token());
  }
  if (from._internal_last_version() != 0) {
    _this->_internal_set_last_version(from._internal_last_version());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PolicySubscription::CopyFrom(const PolicySubscription& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ddrl.comm.PolicySubscription)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PolicySubscription::IsInitialized() const {
  return true;
}

void PolicySubscription::InternalSwap(PolicySubscription* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.worker_id_, lhs_arena,
      &other->_impl_.worker_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.session_token_, lhs_arena,
      &other->_impl_.session_token_, rhs_arena
  );
  swap(_impl_.last_version_, other->_impl_.last_version_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PolicySubscription::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_policy_2eproto_getter, &descriptor_table_policy_2eproto_once,
      file_level_metadata_policy_2eproto[3]);
}

// ===================================================================

class PolicyAck::_Internal {
 public:
};

PolicyAck::PolicyAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ddrl.comm.PolicyAck)
}
PolicyAck::PolicyAck(const PolicyAck& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PolicyAck* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.worker_id_){}
    , decltype(_impl_.version_){}
    , decltype(_impl_.received_unix_ms_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_worker_id().empty()) {
    _this->_impl_.worker_id_.Set(from._internal_worker_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.version_, &from._impl_.version_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.received_unix_ms_) -
    reinterpret_cast<char*>(&_impl_.version_)) + sizeof(_impl_.received_unix_ms_));
  // @@protoc_insertion_point(copy_constructor:ddrl.comm.PolicyAck)
}

inline void PolicyAck::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.worker_id_){}
    , decltype(_impl_.version_){uint64_t{0u}}
    , decltype(_impl_.received_unix_ms_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PolicyAck::~PolicyAck() {
  // @@protoc_insertion_point(destructor:ddrl.comm.PolicyAck)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PolicyAck::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.worker_id_.Destroy();
}

void PolicyAck::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PolicyAck::Clear() {
// @@protoc_insertion_point(message_clear_start:ddrl.comm.PolicyAck)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.worker_id_.ClearToEmpty();
  ::memset(&_impl_.version_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.received_unix_ms_) -
      reinterpret_cast<char*>(&_impl_.version_)) + sizeof(_impl_.received_unix_ms_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PolicyAck::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string worker_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_worker_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ddrl.comm.PolicyAck.worker_id"));
        } else
          goto handle_unusual;
        continue;
      // uint64 version = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 received_unix_ms = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.received_unix_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PolicyAck::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ddrl.comm.PolicyAck)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string worker_id = 1;
  if (!this->_internal_worker_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_worker_id().data(), static_cast<int>(this->_internal_worker_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ddrl.comm.PolicyAck.worker_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_worker_id(), target);
  }

  // uint64 version = 2;
  if (this->_internal_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_version(), target);
  }

  // uint64 received_unix_ms = 3;
  if (this->_internal_received_unix_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_received_unix_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ddrl.comm.PolicyAck)
  return target;
}

size_t PolicyAck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ddrl.comm.PolicyAck)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string worker_id = 1;
  if (!this->_internal_worker_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_worker_id());
  }

  // uint64 version = 2;
  if (this->_internal_version() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_version());
  }

  // uint64 received_unix_ms = 3;
  if (this->_internal_received_unix_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_received_unix_ms());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PolicyAck::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PolicyAck::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PolicyAck::GetClassData() const { return &_class_data_; }


void PolicyAck::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PolicyAck*>(&to_msg);
  auto& from = static_cast<const PolicyAck&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ddrl.comm.PolicyAck)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_worker_id().empty()) {
    _this->_internal_set_worker_id(from._internal_worker_id());
  }
  if (from._internal_version() != 0) {
    _this->_internal_set_version(from._internal_version());
  }
  if (from._internal_received_unix_ms() != 0) {
    _this->_internal_set_received_unix_ms(from._internal_received_unix_ms());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PolicyAck::CopyFrom(const PolicyAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ddrl.comm.PolicyAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PolicyAck::IsInitialized() const {
  return true;
}

void PolicyAck::InternalSwap(PolicyAck* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.worker_id_, lhs_arena,
      &other->_impl_.worker_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PolicyAck, _impl_.received_unix_ms_)
      + sizeof(PolicyAck::_impl_.received_unix_ms_)
      - PROTOBUF_FIELD_OFFSET(PolicyAck, _impl_.version_)>(
          reinterpret_cast<char*>(&_impl_.version_),
          reinterpret_cast<char*>(&other->_impl_.version_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PolicyAck::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_policy_2eproto_getter, &descriptor_table_policy_2eproto_once,
      file_level_metadata_policy_2eproto[4]);
}

// ===================================================================

class PolicyStreamRequest::_Internal {
 public:
  static const ::ddrl::comm::PolicySubscription& subscribe(const PolicyStreamRequest* msg);
  static const ::ddrl::comm::PolicyAck& ack(const PolicyStreamRequest* msg);
};

const ::ddrl::comm::PolicySubscription&
PolicyStreamRequest::_Internal::subscribe(const PolicyStreamRequest* msg) {
  return *msg->_impl_.payload_.subscribe_;
}
const ::ddrl::comm::PolicyAck&
PolicyStreamRequest::_Internal::ack(const PolicyStreamRequest* msg) {
  return *msg->_impl_.payload_.ack_;
}
void PolicyStreamRequest::set_allocated_subscribe(::ddrl::comm::PolicySubscription* subscribe) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (subscribe) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(subscribe);
    if (message_arena != submessage_arena) {
      subscribe = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, subscribe, submessage_arena);
    }
    set_has_subscribe();
    _impl_.payload_.subscribe_ = subscribe;
  }
  // @@protoc_insertion_point(field_set_allocated:ddrl.comm.PolicyStreamRequest.subscribe)
}
void PolicyStreamRequest::set_allocated_ack(::ddrl::comm::PolicyAck* ack) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (ack) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(ack);
    if (message_arena != submessage_arena) {
      ack = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ack, submessage_arena);
    }
    set_has_ack();
    _impl_.payload_.ack_ = ack;
  }
  // @@protoc_insertion_point(field_set_allocated:ddrl.comm.PolicyStreamRequest.ack)
}
PolicyStreamRequest::PolicyStreamRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ddrl.comm.PolicyStreamRequest)
}
PolicyStreamRequest::PolicyStreamRequest(const PolicyStreamRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PolicyStreamRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_payload();
  switch (from.payload_case()) {
    case kSubscribe: {
      _this->_internal_mutable_subscribe()->::ddrl::comm::PolicySubscription::MergeFrom(
          from._internal_subscribe());
      break;
    }
    case kAck: {
      _this->_internal_mutable_ack()->::ddrl::comm::PolicyAck::MergeFrom(
          from._internal_ack());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:ddrl.comm.PolicyStreamRequest)
}

inline void PolicyStreamRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_payload();
}

PolicyStreamRequest::~PolicyStreamRequest() {
  // @@protoc_insertion_point(destructor:ddrl.comm.PolicyStreamRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PolicyStreamRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_payload()) {
    clear_payload();
  }
}

void PolicyStreamRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PolicyStreamRequest::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:ddrl.comm.PolicyStreamRequest)
  switch (payload_case()) {
    case kSubscribe: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.subscribe_;
      }
      break;
    }
    case kAck: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.ack_;
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


void PolicyStreamRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ddrl.comm.PolicyStreamRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_payload();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PolicyStreamRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ddrl.comm.PolicySubscription subscribe = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_subscribe(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ddrl.comm.PolicyAck ack = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_ack(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PolicyStreamRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ddrl.comm.PolicyStreamRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ddrl.comm.PolicySubscription subscribe = 1;
  if (_internal_has_subscribe()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::subscribe(this),
        _Internal::subscribe(this).GetCachedSize(), target, stream);
  }

  // .ddrl.comm.PolicyAck ack = 2;
  if (_internal_has_ack()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::ack(this),
        _Internal::ack(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ddrl.comm.PolicyStreamRequest)
  return target;
}

size_t PolicyStreamRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ddrl.comm.PolicyStreamRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (payload_case()) {
    // .ddrl.comm.PolicySubscription subscribe = 1;
    case kSubscribe: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.subscribe_);
      break;
    }
    // .ddrl.comm.PolicyAck ack = 2;
    case kAck: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.ack_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PolicyStreamRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PolicyStreamRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PolicyStreamRequest::GetClassData() const { return &_class_data_; }


void PolicyStreamRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PolicyStreamRequest*>(&to_msg);
  auto& from = static_cast<const PolicyStreamRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ddrl.comm.PolicyStreamRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.payload_case()) {
    case kSubscribe: {
      _this->_internal_mutable_subscribe()->::ddrl::comm::PolicySubscription::MergeFrom(
          from._internal_subscribe());
      break;
    }
    case kAck: {
      _this->_internal_mutable_ack()->::ddrl::comm::PolicyAck::MergeFrom(
          from._internal_ack());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PolicyStreamRequest::CopyFrom(const PolicyStreamRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ddrl.comm.PolicyStreamRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PolicyStreamRequest::IsInitialized() const {
  return true;
}

void PolicyStreamRequest::InternalSwap(PolicyStreamRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata PolicyStreamRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_policy_2eproto_getter, &descriptor_table_policy_2eproto_once,
      file_level_metadata_policy_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace comm
}  // namespace ddrl
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ddrl::comm::PolicyTensor*
Arena::CreateMaybeMessage< ::ddrl::comm::PolicyTensor >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ddrl::comm::PolicyTensor >(arena);
}
template<> PROTOBUF_NOINLINE ::ddrl::comm::PolicyPush_ScalarsEntry_DoNotUse*
Arena::CreateMaybeMessage< ::ddrl::comm::PolicyPush_ScalarsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ddrl::comm::PolicyPush_ScalarsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::ddrl::comm::PolicyPush*
Arena::CreateMaybeMessage< ::ddrl::comm::PolicyPush >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ddrl::comm::PolicyPush >(arena);
}
template<> PROTOBUF_NOINLINE ::ddrl::comm::PolicySubscription*
Arena::CreateMaybeMessage< ::ddrl::comm::PolicySubscription >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ddrl::comm::PolicySubscription >(arena);
}
template<> PROTOBUF_NOINLINE ::ddrl::comm::PolicyAck*
Arena::CreateMaybeMessage< ::ddrl::comm::PolicyAck >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ddrl::comm::PolicyAck >(arena);
}
template<> PROTOBUF_NOINLINE ::ddrl::comm::PolicyStreamRequest*
Arena::CreateMaybeMessage< ::ddrl::comm::PolicyStreamRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ddrl::comm::PolicyStreamRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
