// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: policy.proto
#ifndef GRPC_policy_2eproto__INCLUDED
#define GRPC_policy_2eproto__INCLUDED

#include "policy.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ddrl {
namespace comm {

class PolicyService final {
 public:
  static constexpr char const* service_full_name() {
    return "ddrl.comm.PolicyService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>> StreamPolicyUpdates(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>>(StreamPolicyUpdatesRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>> AsyncStreamPolicyUpdates(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>>(AsyncStreamPolicyUpdatesRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>> PrepareAsyncStreamPolicyUpdates(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>>(PrepareAsyncStreamPolicyUpdatesRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamPolicyUpdates(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ddrl::comm::PolicyStreamRequest,::ddrl::comm::PolicyPush>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>* StreamPolicyUpdatesRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>* AsyncStreamPolicyUpdatesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>* PrepareAsyncStreamPolicyUpdatesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>> StreamPolicyUpdates(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>>(StreamPolicyUpdatesRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>> AsyncStreamPolicyUpdates(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>>(AsyncStreamPolicyUpdatesRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>> PrepareAsyncStreamPolicyUpdates(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>>(PrepareAsyncStreamPolicyUpdatesRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamPolicyUpdates(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ddrl::comm::PolicyStreamRequest,::ddrl::comm::PolicyPush>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>* StreamPolicyUpdatesRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>* AsyncStreamPolicyUpdatesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>* PrepareAsyncStreamPolicyUpdatesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamPolicyUpdates_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamPolicyUpdates(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ddrl::comm::PolicyPush, ::ddrl::comm::PolicyStreamRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamPolicyUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamPolicyUpdates() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamPolicyUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPolicyUpdates(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::PolicyPush, ::ddrl::comm::PolicyStreamRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamPolicyUpdates(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::ddrl::comm::PolicyPush, ::ddrl::comm::PolicyStreamRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamPolicyUpdates<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamPolicyUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamPolicyUpdates() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamPolicyUpdates(context); }));
    }
    ~WithCallbackMethod_StreamPolicyUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPolicyUpdates(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::PolicyPush, ::ddrl::comm::PolicyStreamRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::ddrl::comm::PolicyStreamRequest, ::ddrl::comm::PolicyPush>* StreamPolicyUpdates(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_StreamPolicyUpdates<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamPolicyUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamPolicyUpdates() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamPolicyUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPolicyUpdates(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::PolicyPush, ::ddrl::comm::PolicyStreamRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamPolicyUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamPolicyUpdates() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamPolicyUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPolicyUpdates(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::PolicyPush, ::ddrl::comm::PolicyStreamRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamPolicyUpdates(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamPolicyUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamPolicyUpdates() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamPolicyUpdates(context); }));
    }
    ~WithRawCallbackMethod_StreamPolicyUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPolicyUpdates(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::PolicyPush, ::ddrl::comm::PolicyStreamRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamPolicyUpdates(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace comm
}  // namespace ddrl


#endif  // GRPC_policy_2eproto__INCLUDED
