// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rollouts.proto
#ifndef GRPC_rollouts_2eproto__INCLUDED
#define GRPC_rollouts_2eproto__INCLUDED

#include "rollouts.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ddrl {
namespace comm {

class RolloutStream final {
 public:
  static constexpr char const* service_full_name() {
    return "ddrl.comm.RolloutStream";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>> StreamRollouts(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>>(StreamRolloutsRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>> AsyncStreamRollouts(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>>(AsyncStreamRolloutsRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>> PrepareAsyncStreamRollouts(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>>(PrepareAsyncStreamRolloutsRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamRollouts(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ddrl::comm::RolloutStreamRequest,::ddrl::comm::RolloutStreamResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>* StreamRolloutsRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>* AsyncStreamRolloutsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>* PrepareAsyncStreamRolloutsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>> StreamRollouts(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>>(StreamRolloutsRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>> AsyncStreamRollouts(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>>(AsyncStreamRolloutsRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>> PrepareAsyncStreamRollouts(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>>(PrepareAsyncStreamRolloutsRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamRollouts(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ddrl::comm::RolloutStreamRequest,::ddrl::comm::RolloutStreamResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>* StreamRolloutsRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>* AsyncStreamRolloutsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>* PrepareAsyncStreamRolloutsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamRollouts_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamRollouts(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ddrl::comm::RolloutStreamResponse, ::ddrl::comm::RolloutStreamRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamRollouts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamRollouts() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamRollouts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamRollouts(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::RolloutStreamResponse, ::ddrl::comm::RolloutStreamRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamRollouts(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::ddrl::comm::RolloutStreamResponse, ::ddrl::comm::RolloutStreamRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamRollouts<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamRollouts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamRollouts() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamRollouts(context); }));
    }
    ~WithCallbackMethod_StreamRollouts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamRollouts(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::RolloutStreamResponse, ::ddrl::comm::RolloutStreamRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>* StreamRollouts(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_StreamRollouts<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamRollouts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamRollouts() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamRollouts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamRollouts(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::RolloutStreamResponse, ::ddrl::comm::RolloutStreamRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamRollouts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamRollouts() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamRollouts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamRollouts(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::RolloutStreamResponse, ::ddrl::comm::RolloutStreamRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamRollouts(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamRollouts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamRollouts() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamRollouts(context); }));
    }
    ~WithRawCallbackMethod_StreamRollouts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamRollouts(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ddrl::comm::RolloutStreamResponse, ::ddrl::comm::RolloutStreamRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamRollouts(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace comm
}  // namespace ddrl


#endif  // GRPC_rollouts_2eproto__INCLUDED
