// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rollouts.proto

#include "rollouts.pb.h"
#include "rollouts.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ddrl {
namespace comm {

static const char* RolloutStream_method_names[] = {
  "/ddrl.comm.RolloutStream/StreamRollouts",
};

std::unique_ptr< RolloutStream::Stub> RolloutStream::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RolloutStream::Stub> stub(new RolloutStream::Stub(channel, options));
  return stub;
}

RolloutStream::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamRollouts_(RolloutStream_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>* RolloutStream::Stub::StreamRolloutsRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>::Create(channel_.get(), rpcmethod_StreamRollouts_, context);
}

void RolloutStream::Stub::async::StreamRollouts(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ddrl::comm::RolloutStreamRequest,::ddrl::comm::RolloutStreamResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::ddrl::comm::RolloutStreamRequest,::ddrl::comm::RolloutStreamResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamRollouts_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>* RolloutStream::Stub::AsyncStreamRolloutsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>::Create(channel_.get(), cq, rpcmethod_StreamRollouts_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>* RolloutStream::Stub::PrepareAsyncStreamRolloutsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>::Create(channel_.get(), cq, rpcmethod_StreamRollouts_, context, false, nullptr);
}

RolloutStream::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RolloutStream_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< RolloutStream::Service, ::ddrl::comm::RolloutStreamRequest, ::ddrl::comm::RolloutStreamResponse>(
          [](RolloutStream::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::ddrl::comm::RolloutStreamResponse,
             ::ddrl::comm::RolloutStreamRequest>* stream) {
               return service->StreamRollouts(ctx, stream);
             }, this)));
}

RolloutStream::Service::~Service() {
}

::grpc::Status RolloutStream::Service::StreamRollouts(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ddrl::comm::RolloutStreamResponse, ::ddrl::comm::RolloutStreamRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ddrl
}  // namespace comm

